/**
 * Seed missing Claude ecosystem terms: Skills, Connectors, Artifacts, Projects, etc.
 * Run: ./node_modules/.bin/tsx --env-file=.env.local scripts/seed-claude-terms.ts
 */

import { createClient } from '@supabase/supabase-js'

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)

const TERMS = [
  {
    slug: 'skill',
    name: 'Skills',
    aliases: ['Claude Skills', 'Claude.ai skill'],
    cluster: 'Tools & Ecosystem',
    scope: 'technical',
    lifecycle_stage: 'adoption',
    audience: ['operator', 'user'],
    tier: 2,
    angles: ['def', 'process', 'role'],
    related_terms: ['connector', 'artifact', 'claude-projects', 'tool-use'],
    claude_specific: true,
    definition: 'Skills are pre-built capabilities you can enable in Claude.ai — things like searching the web, running code, generating images, or reading files. Think of them as apps you turn on inside Claude. Each skill gives Claude access to a specific tool it can use during your conversation. You pick which ones to enable, and Claude will use them automatically when they\'re relevant.',
    published: true,
  },
  {
    slug: 'connector',
    name: 'Connectors',
    aliases: ['Claude Connectors', 'Claude.ai connector'],
    cluster: 'Tools & Ecosystem',
    scope: 'technical',
    lifecycle_stage: 'adoption',
    audience: ['operator', 'user'],
    tier: 2,
    angles: ['def', 'process', 'role'],
    related_terms: ['skill', 'mcp', 'tool-use', 'claude-projects'],
    claude_specific: true,
    definition: 'Connectors link Claude.ai to external services — Google Drive, Dropbox, Jira, GitHub, Notion, and others. Once you connect a service, Claude can read documents from it, search it, or take actions within it during your conversation. It\'s how you give Claude access to your actual work, not just what you paste in.',
    published: true,
  },
  {
    slug: 'artifact',
    name: 'Artifacts',
    aliases: ['Claude Artifacts'],
    cluster: 'Tools & Ecosystem',
    scope: 'technical',
    lifecycle_stage: 'adoption',
    audience: ['user'],
    tier: 2,
    angles: ['def', 'process'],
    related_terms: ['skill', 'claude-projects'],
    claude_specific: true,
    definition: 'Artifacts are self-contained outputs Claude creates in a separate panel alongside your conversation — websites, interactive tools, code files, documents, data visualisations. Instead of just getting text you copy-paste, you get a working thing you can preview, edit, and download. Useful for anything that\'s more than a message: a calculator, a form, a landing page, a spreadsheet template.',
    published: true,
  },
  {
    slug: 'claude-projects',
    name: 'Projects',
    aliases: ['Claude Projects'],
    cluster: 'Tools & Ecosystem',
    scope: 'technical',
    lifecycle_stage: 'adoption',
    audience: ['operator', 'user'],
    tier: 2,
    angles: ['def', 'process', 'role'],
    related_terms: ['connector', 'skill', 'system-prompt', 'context-window'],
    claude_specific: true,
    definition: 'Projects are persistent workspaces inside Claude.ai. Each project gets its own custom instructions, its own set of documents and files, and its own conversation history. Think of it as a dedicated assistant for a specific purpose — your marketing project brief, your company\'s support agent, your engineering runbook. Everything stays in one place and carries forward across sessions.',
    published: true,
  },
  {
    slug: 'extended-thinking',
    name: 'Extended Thinking',
    aliases: ['extended thinking mode', 'Claude thinking mode'],
    cluster: 'Foundation Models & LLMs',
    scope: 'technical',
    lifecycle_stage: 'adoption',
    audience: ['operator', 'developer'],
    tier: 3,
    angles: ['def', 'process', 'role'],
    related_terms: ['adaptive-thinking', 'chain-of-thought', 'reasoning', 'context-window'],
    claude_specific: true,
    definition: 'Extended thinking is a mode where Claude works through a problem step-by-step before giving its final answer. You see its reasoning process — including the parts where it changes its mind or catches an error. It takes longer and costs more tokens, but produces meaningfully better results on hard problems: complex analysis, multi-step planning, tricky reasoning tasks. Turn it on when accuracy matters more than speed.',
    published: true,
  },
  {
    slug: 'adaptive-thinking',
    name: 'Adaptive Thinking',
    aliases: [],
    cluster: 'Foundation Models & LLMs',
    scope: 'technical',
    lifecycle_stage: 'adoption',
    audience: ['operator', 'developer'],
    tier: 3,
    angles: ['def', 'process'],
    related_terms: ['extended-thinking', 'reasoning', 'context-window'],
    claude_specific: true,
    definition: 'Adaptive thinking is how Claude automatically decides how much reasoning effort to apply to a given question. Simple questions get fast, direct answers. Complex or ambiguous questions trigger more deliberate internal reasoning before a response. You don\'t have to configure this — Claude adjusts on its own. The practical result is that you get appropriate depth without having to manually switch modes or prompt for step-by-step reasoning.',
    published: true,
  },
  {
    slug: 'claude-code',
    name: 'Claude Code',
    aliases: ['Claude Code CLI'],
    cluster: 'Tools & Ecosystem',
    scope: 'technical',
    lifecycle_stage: 'adoption',
    audience: ['developer'],
    tier: 2,
    angles: ['def', 'process', 'role'],
    related_terms: ['claude-agent-sdk', 'tool-use', 'mcp'],
    claude_specific: true,
    definition: 'Claude Code is a command-line tool that brings Claude directly into your development workflow. You run it in your terminal, point it at a codebase, and Claude can read files, write code, run commands, and navigate your project — all in conversation. It\'s Claude as a pair programmer that can actually see and touch your work, not just read what you paste in.',
    published: true,
  },
  {
    slug: 'claude-agent-sdk',
    name: 'Agent SDK',
    aliases: ['Claude Agent SDK', 'Anthropic Agent SDK'],
    cluster: 'Tools & Ecosystem',
    scope: 'technical',
    lifecycle_stage: 'adoption',
    audience: ['developer'],
    tier: 3,
    angles: ['def', 'process', 'role'],
    related_terms: ['ai-agent', 'tool-use', 'mcp', 'claude-code'],
    claude_specific: true,
    definition: 'The Agent SDK is Anthropic\'s framework for building autonomous AI agents that use Claude as their brain. It handles the mechanics of an agent loop — giving Claude tools, tracking what it\'s done, deciding what to do next — so you can focus on what the agent should accomplish. Use it when you\'re building something where Claude needs to complete multi-step tasks on its own, not just answer a question.',
    published: true,
  },
  {
    slug: 'prompt-caching',
    name: 'Prompt Caching',
    aliases: ['context caching'],
    cluster: 'Tools & Ecosystem',
    scope: 'technical',
    lifecycle_stage: 'adoption',
    audience: ['developer', 'operator'],
    tier: 4,
    angles: ['def', 'process'],
    related_terms: ['context-window', 'system-prompt', 'token'],
    claude_specific: true,
    definition: 'Prompt caching saves a portion of your prompt — typically a large system prompt or document — so Claude doesn\'t need to re-process it on every request. The first call includes the full context; subsequent calls reference the cached version. The practical effect: faster responses and lower API costs when you\'re repeatedly sending the same long context, which is common in production applications.',
    published: true,
  },
  {
    slug: 'hallucination',
    name: 'Hallucination',
    aliases: ['confabulation', 'AI hallucination'],
    cluster: 'Foundation Models & LLMs',
    scope: 'conceptual',
    lifecycle_stage: 'adoption',
    audience: ['all'],
    tier: 1,
    angles: ['def', 'failure', 'role'],
    related_terms: ['rag', 'grounding', 'evals', 'system-prompt'],
    claude_specific: false,
    definition: 'Hallucination is when an AI model states something confidently that isn\'t true. It might invent a citation, get a date wrong, describe a product feature that doesn\'t exist, or fill in gaps in its knowledge with plausible-sounding guesses. It happens because language models are trained to produce fluent text — not to verify facts before speaking. Knowing when to trust Claude\'s output versus when to ground it in real sources is one of the most important skills for operators.',
    published: true,
  },
  {
    slug: 'context-window',
    name: 'Context Window',
    aliases: ['context length', 'token limit'],
    cluster: 'Foundation Models & LLMs',
    scope: 'conceptual',
    lifecycle_stage: 'adoption',
    audience: ['all'],
    tier: 1,
    angles: ['def', 'process', 'role'],
    related_terms: ['token', 'prompt-caching', 'rag', 'system-prompt'],
    claude_specific: false,
    definition: 'The context window is how much text Claude can hold in its attention at once — your conversation history, any documents you\'ve shared, system instructions, and Claude\'s own responses. Once you hit the limit, older content gets pushed out. Claude 3.7 Sonnet has a 200,000-token context window, which is roughly 150,000 words. Long contexts let Claude analyse full documents or maintain long conversations — but they also cost more and can sometimes cause Claude to lose focus on earlier material.',
    published: true,
  },
  {
    slug: 'system-prompt',
    name: 'System Prompt',
    aliases: ['system instruction', 'system message'],
    cluster: 'Tools & Ecosystem',
    scope: 'conceptual',
    lifecycle_stage: 'adoption',
    audience: ['operator', 'developer'],
    tier: 2,
    angles: ['def', 'process', 'role'],
    related_terms: ['prompt-caching', 'context-window', 'tool-use', 'operator'],
    claude_specific: false,
    definition: 'A system prompt is the set of instructions you give Claude before the conversation starts — telling it who it is, what it\'s for, what it should and shouldn\'t do, and how to behave. Users see the conversation; they typically don\'t see the system prompt. It\'s the configuration layer between you as an operator and Claude as a product. Writing a good system prompt is one of the highest-leverage things you can do when deploying Claude.',
    published: true,
  },
  {
    slug: 'mcp',
    name: 'Model Context Protocol',
    aliases: ['MCP', 'MCP connector'],
    cluster: 'Tools & Ecosystem',
    scope: 'technical',
    lifecycle_stage: 'adoption',
    audience: ['developer', 'operator'],
    tier: 3,
    angles: ['def', 'process', 'role'],
    related_terms: ['connector', 'tool-use', 'ai-agent', 'claude-code'],
    claude_specific: false,
    definition: 'MCP (Model Context Protocol) is an open standard that defines how AI models connect to external data sources and tools. Instead of every developer building their own custom integration, MCP gives a universal interface: if a tool supports MCP, any MCP-compatible AI can use it. Anthropic created and open-sourced it. In practice, MCP is what makes it possible for Claude to connect to your file system, your database, your APIs — in a structured, secure way.',
    published: true,
  },
  {
    slug: 'tool-use',
    name: 'Tool Use',
    aliases: ['function calling', 'tool calling'],
    cluster: 'Tools & Ecosystem',
    scope: 'technical',
    lifecycle_stage: 'adoption',
    audience: ['developer', 'operator'],
    tier: 3,
    angles: ['def', 'process', 'role'],
    related_terms: ['mcp', 'ai-agent', 'claude-agent-sdk', 'system-prompt'],
    claude_specific: false,
    definition: 'Tool use lets Claude call external functions and APIs during a conversation. You define the tools Claude has access to — search, database lookup, sending an email, running a calculation — and Claude decides when to call them, what inputs to send, and how to use the results in its response. It\'s the mechanism that turns Claude from a text generator into something that can take actions and interact with real systems.',
    published: true,
  },
  {
    slug: 'rag',
    name: 'RAG',
    aliases: ['Retrieval-Augmented Generation', 'retrieval augmented generation'],
    cluster: 'Tools & Ecosystem',
    scope: 'technical',
    lifecycle_stage: 'adoption',
    audience: ['developer', 'operator'],
    tier: 3,
    angles: ['def', 'process', 'role', 'failure'],
    related_terms: ['context-window', 'tool-use', 'grounding', 'hallucination'],
    claude_specific: false,
    definition: 'RAG (Retrieval-Augmented Generation) is an architecture where Claude retrieves relevant information from an external source before generating a response. Instead of relying purely on training data, Claude searches your documents, database, or knowledge base to find the right context, then uses that to answer. The result: Claude can answer questions about your specific products, policies, or data — things it couldn\'t have known from training alone.',
    published: true,
  },
]

async function main() {
  console.log(`Seeding ${TERMS.length} Claude ecosystem terms...`)

  for (const term of TERMS) {
    const { data, error } = await sb
      .from('terms')
      .upsert({
        ...term,
        updated_at: new Date().toISOString(),
      }, { onConflict: 'slug' })
      .select('slug')

    if (error) {
      console.error(`  ✗ ${term.slug}:`, error.message)
    } else {
      console.log(`  ✓ ${term.slug}`)
    }
  }

  console.log('\nDone.')
}

main().catch(console.error)
