/**
 * Batch 70 — Managed Agents memory stores + MCP production agents (April 22–23, 2026)
 *
 * 1. claude-managed-agents-memory
 *    Memory stores for Managed Agents entered public beta April 23, 2026.
 *    Workspace-scoped document collections the agent reads/writes across sessions.
 *    DEV_SLUGS. Cluster: Claude API.
 *
 * 2. mcp-production-agents
 *    Sourced from the April 22, 2026 blog post "Building agents that reach production
 *    systems with MCP". Developer implementation guide: auth, scoping, error handling.
 *    DEV_SLUGS. Cluster: Agents & Tools.
 *
 * Run: ./node_modules/.bin/tsx --env-file=.env.local scripts/seed-articles-70.ts
 */

import { createClient } from '@supabase/supabase-js'

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)

async function getTermId(slug: string): Promise<{ id: string; name: string } | null> {
  const { data } = await sb.from('terms').select('id, name').eq('slug', slug).single()
  return data
}

const articles = [
  {
    slug: 'claude-managed-agents-memory',
    angle: 'update',
    title: 'Persistent Memory for Claude Managed Agents',
    excerpt: "By default, a Managed Agents session starts fresh and forgets everything when it ends. Memory stores change that — they're workspace-scoped document collections the agent reads and writes across sessions. The feature entered public beta on April 23, 2026.",
    readTime: 8,
    cluster: 'Claude API',
    audience: ['developer'],
    termSlug: 'ai-agent',
    body: `Claude Managed Agents sessions start with a blank context by default. When a session ends, anything the agent learned is gone. Memory stores let you carry information across sessions: user preferences, project conventions, prior mistakes, domain knowledge.

Memory entered public beta on April 23, 2026, under the existing \`managed-agents-2026-04-01\` beta header — no additional header required.

## How memory stores work

A **memory store** is a workspace-scoped collection of text documents. When you attach a store to a session, it mounts as a directory inside the session's container at \`/mnt/memory/\`. The agent reads and writes it using the same file tools it uses for the rest of the filesystem. A short description of each mount is automatically added to the system prompt so the agent knows where to look.

Every write creates an immutable **memory version** — an audit trail and point-in-time recovery for everything the agent changes.

Individual memory files are capped at 100KB (~25K tokens). Store many small focused files rather than a few large ones.

## Create a memory store

Give the store a name and a description. The description tells the agent what the store contains.

\`\`\`typescript
const store = await client.beta.memoryStores.create({
  name: "User Preferences",
  description: "Per-user preferences and project context."
});
console.log(store.id); // memstore_01Hx...
\`\`\`

The store ID (\`memstore_...\`) is what you pass when attaching to a session.

## Seed a store with content

Pre-load reference material before any agent session runs:

\`\`\`typescript
await client.beta.memoryStores.memories.create(store.id, {
  path: "/formatting_standards.md",
  content: "All reports use GAAP formatting. Dates are ISO-8601..."
});
\`\`\`

Useful for organizational standards, domain conventions, or any reference material that doesn't need to be generated by the agent — just read.

## Attach to a session

Memory stores are attached in the session's \`resources[]\` array at creation time. You cannot add or remove a store from a running session.

\`\`\`typescript
const session = await client.beta.sessions.create({
  agent: agent.id,
  environment_id: environment.id,
  resources: [
    {
      type: "memory_store",
      memory_store_id: store.id,
      access: "read_write",
      instructions: "User preferences and project context. Check before starting any task."
    }
  ]
});
\`\`\`

\`access\` defaults to \`read_write\`. Set it to \`read_only\` for reference stores the agent should consult but not change.

Up to 8 memory stores can be attached per session.

## Access patterns

**One store per user.** If you're building a multi-user product, create a separate store per end user keyed to their user ID. Each session for that user attaches their store. The agent picks up prior context — their preferences, past decisions — without you building a retrieval layer.

**One shared read-only store + per-user read-write store.** Common pattern: one store for organizational standards (read-only, shared across all sessions) and one store per user for their personal context (read-write). Attach both to every session.

\`\`\`typescript
const session = await client.beta.sessions.create({
  agent: agent.id,
  environment_id: environment.id,
  resources: [
    {
      type: "memory_store",
      memory_store_id: orgStoreId,
      access: "read_only",
      instructions: "Organizational formatting and compliance standards."
    },
    {
      type: "memory_store",
      memory_store_id: userStoreId,
      access: "read_write",
      instructions: "This user's preferences and project context. Update when the user states a preference."
    }
  ]
});
\`\`\`

## Reading and editing memories via the API

You can inspect and correct memories directly — no session needed.

**List memories in a store:**
\`\`\`typescript
const page = await client.beta.memoryStores.memories.list(store.id, {
  path_prefix: "/",
  order_by: "path",
  depth: 2
});
for (const item of page.data) {
  console.log(item.type, item.path);
}
\`\`\`

**Read a specific memory:**
\`\`\`typescript
const mem = await client.beta.memoryStores.memories.retrieve(memId, {
  memory_store_id: store.id
});
console.log(mem.content);
\`\`\`

**Update a memory with an optimistic concurrency check:**
\`\`\`typescript
// Pass content_sha256 to prevent clobbering a concurrent write.
// On hash mismatch, re-read and retry.
await client.beta.memoryStores.memories.update(mem.id, {
  memory_store_id: store.id,
  content: "CORRECTED: Always use 2-space indentation.",
  precondition: { type: "content_sha256", content_sha256: mem.content_sha256 }
});
\`\`\`

## Security: prompt injection risk

Memory stores attach with \`read_write\` access by default. If the agent processes untrusted input — user-supplied prompts, fetched web content, third-party tool output — a successful prompt injection could write malicious content into the store. Future sessions then read that content as trusted memory.

Use \`read_only\` for:
- Reference material and shared lookups
- Any store the agent doesn't need to modify
- Stores shared across many sessions

Audit what the agent has written with the memory versions API before relying on store contents in production.

## Audit trail and version history

Every mutation creates a memory version (\`memver_...\`). Versions survive even after the memory is deleted.

\`\`\`typescript
// List version history for a memory
for await (const v of client.beta.memoryStores.memoryVersions.list(store.id, {
  memory_id: mem.id
})) {
  console.log(\`\${v.id}: \${v.operation}\`);
}
\`\`\`

To roll back: retrieve the version you want and write its content back with \`memories.update\`.

For compliance workflows — removing leaked secrets or PII — use the redact endpoint to scrub content from a historical version while preserving the audit record.

Version history is retained for 30 days.

## Limits (public beta)

| Limit | Value |
|---|---|
| Memory stores per organization | 1,000 |
| Memories per store | 2,000 |
| Total storage per store | 100 MB |
| Size per memory | 100 KB (~25K tokens) |
| Stores per session | 8 |
| Version history retention | 30 days |

## What to read next

- [Claude Managed Agents](/articles/claude-managed-agents) — Managed Agents overview: setup, sessions, tools
- [Multi-agent orchestration](/articles/multi-agent-orchestration-basics) — coordinating agents when memory alone isn't enough
- [Securing your Claude app](/articles/securing-your-claude-app) — prompt injection and production security patterns

---

*Memory for Claude Managed Agents entered public beta April 23, 2026. See the [API release notes](https://platform.claude.com/docs/en/release-notes/overview) and [integration guide](https://platform.claude.com/docs/en/managed-agents/memory).*`,
  },
  {
    slug: 'mcp-production-agents',
    angle: 'process',
    title: 'Connecting Claude Agents to Production Systems with MCP',
    excerpt: "The MCP connector lets a Claude agent reach live production systems — CRMs, databases, internal APIs — at runtime, without you building custom tool integrations for each one. Here's how to structure that connection safely and what breaks when you don't.",
    readTime: 9,
    cluster: 'Agents & Tools',
    audience: ['developer'],
    termSlug: 'mcp',
    body: `Model Context Protocol (MCP) is a standard for connecting AI agents to external systems. Claude supports it natively via the MCP connector in the Messages API and as a built-in capability in Claude Managed Agents. As of February 2026, the connector is generally available — no beta header required.

This guide covers the implementation decisions that matter when you're connecting agents to production systems: authentication, permission scoping, error handling, and the failure modes that show up in real deployments.

## What MCP gives you

Without MCP, connecting Claude to an external system means writing a custom tool — a function that calls the API, handles auth, formats the response, and returns structured data. That's one tool per integration.

MCP lets external systems expose their own tools through a standard server interface. Claude connects to the MCP server at session time and discovers what tools are available. You configure the connection; the tool definitions come from the server.

For a single-integration agent this barely matters. For an agent that needs to touch five systems — a CRM, a ticketing tool, a database, a docs platform, and an internal API — MCP eliminates five separate tool implementations.

## Connecting to an MCP server in Claude Managed Agents

In Claude Managed Agents, MCP servers are attached at agent creation time:

\`\`\`typescript
const agent = await client.beta.agents.create({
  model: "claude-opus-4-7-20260416",
  name: "Sales Research Agent",
  system: "You are a sales research assistant with access to our CRM and knowledge base.",
  mcp_servers: [
    {
      type: "url",
      url: "https://crm.internal.example.com/mcp",
      name: "CRM",
      authorization_token: process.env.CRM_MCP_TOKEN
    },
    {
      type: "url",
      url: "https://docs.internal.example.com/mcp",
      name: "KnowledgeBase",
      authorization_token: process.env.DOCS_MCP_TOKEN
    }
  ]
});
\`\`\`

The agent discovers available tools from each server when a session starts. Claude's system prompt sees the tool names and descriptions from the MCP server's manifest.

## Connecting via the Messages API

For agents built directly on the Messages API, attach MCP servers in the request:

\`\`\`typescript
const response = await client.beta.messages.create({
  model: "claude-sonnet-4-6-20260217",
  max_tokens: 4096,
  mcp_servers: [
    {
      type: "url",
      url: "https://crm.internal.example.com/mcp",
      name: "CRM",
      authorization_token: process.env.CRM_MCP_TOKEN
    }
  ],
  messages: [{ role: "user", content: "Pull the last 30 days of deals for the enterprise segment." }]
}, {
  headers: { "anthropic-beta": "mcp-client-2025-04-04" }
});
\`\`\`

## Authentication patterns

Each MCP server connection takes an \`authorization_token\` passed as a Bearer token. In practice, this maps to three patterns:

**Static API key.** The MCP server validates a long-lived token. Simplest to set up, hardest to rotate. Fine for internal services with tight network controls. Pass the token as an environment variable; never hardcode it.

**Short-lived token per session.** Before creating each session, fetch a fresh token from your auth system and pass it in. The token expires with the session. Better for external-facing deployments where you want clear session boundaries.

\`\`\`typescript
// Fetch a scoped token before each session
const token = await getSessionToken({
  userId: user.id,
  scopes: ["crm:read", "tickets:write"],
  ttl: 3600
});

const session = await client.beta.sessions.create({
  agent: agentId,
  environment_id: envId,
  // Override the agent's default MCP config with a session-scoped token
  mcp_servers: [
    {
      type: "url",
      url: "https://crm.internal.example.com/mcp",
      name: "CRM",
      authorization_token: token
    }
  ]
});
\`\`\`

**OAuth.** For MCP servers that support it, OAuth lets the agent act on behalf of a specific user with that user's permissions. The MCP server handles the OAuth flow; you pass the resulting access token as \`authorization_token\`.

## Scoping permissions

The most common production mistake: attaching a full-access token when the agent only needs read access.

Set the minimum scope the agent needs for its task. If the agent reads deal data to generate reports, give it \`crm:read\` — not \`crm:admin\`. This matters for two reasons:

**Blast radius.** If the agent misinterprets a task or a user input causes unexpected tool calls, a read-only token limits the damage.

**Prompt injection.** An agent that fetches data from external sources (web pages, emails, documents) can be manipulated by content embedded in that data — instructions disguised as normal content. A narrow-scoped token means a successful injection can only do what the token allows.

Structure your MCP servers to expose scoped surfaces rather than full system access. A CRM server might expose one tool endpoint for deal reads and a separate one for deal writes, each requiring a different scope.

## Error handling

MCP tool calls can fail in ways that don't fail your application — the agent receives the error and decides how to proceed. What you control is what errors look like and how persistent they are.

**Surface useful errors.** When an MCP tool fails, Claude sees the error message in the tool result. If your MCP server returns \`"Internal server error"\`, Claude has nothing actionable. Return structured errors with enough context for the agent to try an alternative: \`"Rate limit reached for crm:search. Try a narrower date range or wait 60 seconds."\`

**Set timeout limits.** Long-running MCP tool calls hold up the session. Configure timeouts on your MCP server and in your session environment. An agent waiting indefinitely on a slow tool call will exhaust your session budget.

**Handle auth failures explicitly.** A 401 from an MCP server should surface as a clear "authentication failed" message, not a generic error. Claude can then tell the user what happened rather than trying to retry indefinitely.

\`\`\`typescript
// In your MCP server handler
if (!isValidToken(req.headers.authorization)) {
  return {
    error: {
      code: "auth_failed",
      message: "MCP authorization token is invalid or expired. Re-authenticate to continue."
    }
  };
}
\`\`\`

## What breaks in production

**Tool discovery drift.** MCP servers can add, remove, or rename tools without warning. If Claude's system prompt references a tool by name that no longer exists, the agent will try it, get an error, and may hallucinate an alternative. Pin your MCP server versions. Run integration tests that verify tool discovery against each connected server.

**Context window pressure.** MCP tool results return full payloads. A CRM tool that returns 200 deal records as JSON can consume tens of thousands of tokens in a single tool call. Design MCP tools to return paginated or filtered results. Pass filtering instructions in the tool's description so Claude uses them.

**Shared MCP servers in multi-tenant deployments.** If multiple users' agent sessions connect to the same MCP server, the server must enforce tenant isolation — Claude cannot do this. The MCP server is responsible for ensuring each token only accesses the right tenant's data.

## Logging and observability

MCP tool calls appear in the Managed Agents event stream as ordinary \`agent.tool_use\` and \`agent.tool_result\` events. Log these — they tell you which tools the agent actually called, with what inputs, and what came back. This is your audit trail for production debugging.

For the Messages API, tool use and results appear in the response \`content\` blocks. Log the full request and response at the application layer.

## What to read next

- [Claude Managed Agents](/articles/claude-managed-agents) — full Managed Agents setup guide
- [Multi-agent failure handling](/articles/multi-agent-failure-handling) — timeout, partial output, and recovery patterns
- [Securing your Claude app](/articles/securing-your-claude-app) — prompt injection defense and production security

---

*This guide is based on the April 22, 2026 Anthropic blog post "Building agents that reach production systems with MCP" and the [MCP connector documentation](https://platform.claude.com/docs/en/agents-and-tools/mcp-connector).*`,
  },
]

async function seed() {
  console.log('Seeding Batch 70 — Managed Agents memory + MCP production agents...\n')

  for (const a of articles) {
    const term = await getTermId(a.termSlug)
    if (!term) {
      console.error(`  ✗ Term not found: ${a.termSlug}`)
      continue
    }

    const payload = {
      slug:      a.slug,
      angle:     a.angle,
      title:     a.title,
      excerpt:   a.excerpt,
      body:      a.body,
      read_time: a.readTime,
      cluster:   a.cluster,
      term_id:   term.id,
      term_name: term.name,
      term_slug: a.termSlug,
      published: true,
    }

    const { error } = await sb.from('articles').upsert(payload, { onConflict: 'slug' })

    if (error) {
      console.error(`  ✗ ${a.slug}: ${error.message}`)
    } else {
      console.log(`  ✓ ${a.slug}`)
    }
  }

  console.log('\nDone.')
}

seed().catch(console.error)
