/**
 * Seed timeline_events table from the original hardcoded EVENTS array.
 * Run: npx tsx scripts/seed-timeline.ts
 */
import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'
import * as path from 'path'

dotenv.config({ path: path.join(__dirname, '../.env.local') })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const EVENTS = [
  // 2026
  { event_date: '2026-04-17', org: 'Anthropic', title: 'Claude Design — visuals, prototypes, and decks from conversation', description: "Anthropic launches Claude Design, an experimental product for creating visual work: prototypes, presentation decks, one-pagers, and UI mockups. Built on Opus 4.7. Users describe what they need, Claude builds a first version, then they refine through conversation or inline edits. Reads a team's design system and codebase for brand consistency. Exports to PDF, URL, PPTX, or Canva. Available to Pro, Max, Team, and Enterprise subscribers.", significance: 'major', href: 'https://techcrunch.com/2026/04/17/anthropic-launches-claude-design-a-new-product-for-creating-quick-visuals/', audience: ['for-you'] },
  { event_date: '2026-04-16', org: 'Anthropic', title: 'Claude Opus 4.7 — sharper vision, better coding, self-verification', description: 'Opus 4.7 upgrades the flagship model with improved agentic coding, multidisciplinary reasoning, scaled tool use, and computer use. New xhigh effort level gives finer latency vs. reasoning control. Maximum image resolution jumps from 1.15MP to 3.75MP (3.3× increase). Pricing unchanged at $5/$25 per million tokens. Available across Claude products, API, Bedrock, Vertex AI, and Microsoft Foundry.', significance: 'major', href: 'https://www.anthropic.com/news/claude-opus-4-7', article_slug: 'claude-opus-4-7', audience: ['for-you', 'for-builders'] },
  { event_date: '2026-04-16', org: 'Meta', title: 'Muse Spark Shopping — AI-native commerce across Meta apps', description: "Meta embeds a shopping experience directly into Muse Spark, rolling out across WhatsApp, Instagram, Facebook, and Messenger. Users get outfit suggestions, room styling help, and gift recommendations in-conversation. First major commerce integration built on a foundation model rather than a separate product layer — a template for how AI interfaces could replace traditional e-commerce flows.", significance: 'notable', href: 'https://www.retailbrew.com/stories/2026/04/16/meta-introduces-new-shopping-upgrades-under-ai-model-muse-spark' },
  { event_date: '2026-04-14', org: 'OpenAI', title: 'GPT-5.4-Cyber — security-focused model with tiered access', description: "OpenAI releases GPT-5.4-Cyber to vetted researchers and security teams, with access tiers that loosen restrictions for verified practitioners doing defensive research. Designed for threat modeling, vulnerability analysis, and exploit documentation — with guardrails calibrated by verification level rather than a single policy. Released in direct response to Anthropic's Mythos Preview from Project Glasswing.", significance: 'notable', href: 'https://www.bloomberg.com/news/articles/2026-04-14/openai-releases-cyber-model-to-limited-group-in-race-with-mythos' },
  { event_date: '2026-04-10', org: 'Anthropic', title: 'Claude for Word — native sidebar in Microsoft Word', description: "Claude launches as a native sidebar add-in for Microsoft Word on Mac and Windows. Highlights passages, rewrites sections, and inserts edits as tracked changes using Word's existing review workflow. Completes Claude's integration across the full Office suite (Excel, PowerPoint, Word). Available to Team and Enterprise plans.", significance: 'notable', href: 'https://www.thurrott.com/a-i/334834/anthropic-launches-claude-for-word-in-beta', audience: ['for-you', 'for-admins'] },
  { event_date: '2026-04-10', org: 'Anthropic', title: 'Ultraplan — cloud-powered planning for Claude Code', description: 'Claude Code gains Ultraplan: a cloud-powered planning mode that uses Claude on the web to generate comprehensive implementation plans before coding begins. Designed for complex, multi-file tasks where getting the architecture right up front saves hours of rework.', significance: 'notable', href: 'https://code.claude.com/docs/en/ultraplan', audience: ['for-builders'] },
  { event_date: '2026-04-09', org: 'Anthropic', title: 'Advisor strategy — Opus intelligence at Sonnet prices', description: 'Anthropic introduces the advisor tool: pair a fast executor model (Sonnet or Haiku) with Opus as a strategic advisor that only gets called on hard decisions. Sonnet + Opus advisor improved SWE-bench Multilingual by 2.7 percentage points while cutting per-task cost by 11.9%. A new paradigm for cost-effective agent intelligence.', significance: 'notable', href: 'https://claude.com/blog/the-advisor-strategy', audience: ['for-builders'] },
  { event_date: '2026-04-09', org: 'Anthropic', title: 'Ask Your Org — org-wide knowledge search across Slack, email, Drive', description: 'Anthropic launches Ask Your Org: a pre-configured Project that searches across connected company tools (Slack, Microsoft 365, Google Workspace, custom MCP connectors) and returns a single synthesized answer with citations. Permission-aware — users only see data they can already access. Available to Team and Enterprise plans after owner setup.', significance: 'major', article_slug: 'ask-your-org-guide', audience: ['for-you', 'for-admins'] },
  { event_date: '2026-04-09', org: 'Anthropic', title: 'New admin controls — user groups, spend limits, Compliance API', description: 'Anthropic ships a batch of admin controls for Team and Enterprise: user groups with SCIM sync, role-based access defining which Claude features each group can use, per-user spend caps, managed Claude Code policies (tool/file/MCP permissions), and a new Compliance API for Enterprise giving programmatic access to usage data and selective deletion.', significance: 'notable', article_slug: 'claude-admin-controls-2026', audience: ['for-admins'] },
  { event_date: '2026-04-09', org: 'Anthropic', title: 'Claude Cowork generally available — enterprise-ready', description: 'Cowork goes GA on macOS and Windows with Analytics API access, OpenTelemetry monitoring, and role-based access controls for enterprise departments. The shift from collaborative experiment to production-grade team workspace.', significance: 'notable', href: 'https://claude.com/blog/cowork-for-enterprise', audience: ['for-you', 'for-admins'] },
  { event_date: '2026-04-09', org: 'Anthropic', title: 'Monitor tool — background streaming in Claude Code', description: 'Claude Code gains the Monitor tool: spawn a background process and stream its stdout into the conversation without blocking the thread. Enables patterns like "watch kubectl logs for errors and fix any crashes" — a step toward always-on agent awareness.', significance: 'notable', href: 'https://code.claude.com/docs/en/changelog', audience: ['for-builders'] },
  { event_date: '2026-04-08', org: 'Meta', title: "Muse Spark — Meta's first proprietary model", description: "Meta launches Muse Spark, its first proprietary (non-open-source) model, developed by Meta Superintelligence Labs. Small and fast, competitive on reasoning and agentic tasks. Signals a strategic shift: Meta now has both open (Llama) and closed model lines.", significance: 'notable' },
  { event_date: '2026-04-08', org: 'Anthropic', title: 'Claude Managed Agents — autonomous agents via API', description: "Anthropic launches Managed Agents in public beta: a fully managed harness for running Claude as an autonomous agent with secure sandboxing, built-in tools, and streaming. Create agents, configure containers, and run sessions entirely through the API. The biggest shift from Claude-as-assistant to Claude-as-worker.", significance: 'major', glossary_slug: 'managed-agents', href: 'https://platform.claude.com/docs/en/managed-agents/overview', audience: ['for-builders'] },
  { event_date: '2026-04-07', org: 'Anthropic', title: 'Project Glasswing — defensive cybersecurity coalition', description: 'Anthropic announces Project Glasswing alongside AWS, Apple, Google, Microsoft, NVIDIA, and others to secure critical software infrastructure. Claude Mythos Preview — a specialized cybersecurity model — available as a gated research preview for defensive work.', significance: 'notable', href: 'https://anthropic.com/glasswing', audience: ['for-admins'] },
  { event_date: '2026-04-07', org: 'Google', title: 'AI Edge Eloquent — offline-first AI dictation for iOS', description: "Google quietly ships AI Edge Eloquent, an on-device dictation app for iOS using Gemma-based speech recognition models. Works fully offline; optional Gemini cloud integration for post-processing. Signals Google's push into private, on-device AI — where inference stays on the hardware rather than hitting a remote API.", significance: 'notable', href: 'https://techcrunch.com/2026/04/07/google-quietly-releases-an-offline-first-ai-dictation-app-on-ios/' },
  { event_date: '2026-04-02', org: 'Google', title: 'Gemma 4 — natively multimodal open model family', description: 'Google releases Gemma 4, an open model family from 2.3B to 31B parameters that is natively multimodal (text, image, video). The 31B Dense variant ranks #3 globally among open models. A major leap in what open-weights models can do.', significance: 'notable' },
  { event_date: '2026-04-02', org: 'Microsoft', title: 'MAI-Transcribe-1, MAI-Voice-1, MAI-Image-2 — three in-house models', description: "Microsoft announces three new proprietary MAI foundation models available in Azure AI Foundry: MAI-Transcribe-1 (state-of-the-art multilingual speech recognition), MAI-Voice-1 (custom voice synthesis), and MAI-Image-2 (top Arena.ai leaderboard scores, 2× faster generation). First clear signal that Microsoft is building its own model stack alongside its OpenAI and Anthropic partnerships.", significance: 'notable', href: 'https://techcrunch.com/2026/04/02/microsoft-takes-on-ai-rivals-with-three-new-foundational-models/' },
  { event_date: '2026-03-13', org: 'Anthropic', title: '1M token context window — generally available', description: 'The 1M token context window is now GA for Claude Opus 4.6 and Sonnet 4.6 at standard pricing — no beta header required. Requests over 200k tokens work automatically. Also raised the media limit from 100 to 600 images or PDF pages per request.', significance: 'notable', href: 'https://platform.claude.com/docs/en/build-with-claude/context-windows', audience: ['for-builders'] },
  { event_date: '2026-03-12', org: 'Anthropic', title: 'Claude Partner Network — $100M enterprise adoption push', description: 'Anthropic launches the Claude Partner Network with $100M invested to accelerate enterprise adoption. Targets system integrators, consultants, and implementation partners helping organizations deploy Claude at scale.', significance: 'notable', href: 'https://www.anthropic.com/news/claude-partner-network', audience: ['for-admins'] },
  { event_date: '2026-02-17', org: 'Anthropic', title: 'Claude Sonnet 4.6 — frontier performance at everyday speed', description: 'Sonnet 4.6 launches as the balanced model for professional work at scale — improved agentic search, fewer tokens consumed, extended thinking support, and 1M token context window. Web search and code execution tools hit general availability on the same day.', significance: 'major', href: 'https://www.anthropic.com/news/claude-sonnet-4-6', audience: ['for-you', 'for-builders'] },
  { event_date: '2026-02-12', org: 'Anthropic', title: 'Series G — $30 billion at $380B valuation', description: "Anthropic raises $30B in Series G funding at a $380B post-money valuation, with $14B annual run-rate revenue. One of the most valuable private companies in history. Signals market conviction that frontier AI will be defining infrastructure.", significance: 'context', href: 'https://www.anthropic.com/news' },
  { event_date: '2026-02-05', org: 'Anthropic', title: 'Claude Opus 4.6 — flagship for long-horizon agents', description: "Opus 4.6 launches for complex, long-horizon agentic tasks. Introduces adaptive thinking (replacing manual budget_tokens), the compaction API for effectively infinite conversations, and data residency controls. Fast mode — up to 2.5x faster — available in preview.", significance: 'major', href: 'https://www.anthropic.com/news/claude-opus-4-6', audience: ['for-you', 'for-builders'] },
  { event_date: '2026-01-13', org: 'Anthropic', title: 'Claude Labs — experimental features platform', description: 'Anthropic launches Labs, a platform for experimental Claude features before they reach the main product. First move toward a formal beta program for early access to capabilities in development.', significance: 'notable', href: 'https://www.anthropic.com/news', audience: ['for-you'] },
  { event_date: '2026-01-11', org: 'Anthropic', title: 'Claude for Healthcare & Life Sciences — HIPAA-ready', description: 'Anthropic launches HIPAA-ready infrastructure with clinical trial connectors for healthcare and life sciences. Opens Claude to regulated industries that previously had compliance blockers.', significance: 'notable', href: 'https://www.anthropic.com/news', audience: ['for-admins'] },
  { event_date: '2026-01-05', org: 'Microsoft', title: 'Copilot for M365 — broad enterprise rollout', description: 'Microsoft Copilot reaches general availability across M365 enterprise. AI embedded in Word, Excel, PowerPoint, Outlook, and Teams. Forces the question: if Copilot is good enough for document work, what does Claude add?', significance: 'notable' },
  // 2025
  { event_date: '2025-12-09', org: 'Anthropic', title: 'MCP donated to the Agentic AI Foundation', description: 'Anthropic donates the Model Context Protocol to the newly formed Agentic AI Foundation, cementing MCP as an open industry standard. Adopted by dozens of companies since its release, MCP becomes a neutral, community-governed protocol.', significance: 'notable', glossary_slug: 'mcp', href: 'https://www.anthropic.com/news', audience: ['for-builders', 'for-admins'] },
  { event_date: '2025-12-01', org: 'Anthropic', title: 'Claude.ai Cowork — shared workspaces for teams', description: 'Real-time collaborative sessions in Claude — multiple users working in the same conversation. Foundation for team-based AI workflows.', significance: 'notable', glossary_slug: 'cowork', audience: ['for-you', 'for-admins'] },
  { event_date: '2025-11-24', org: 'Anthropic', title: 'Claude Opus 4.5 — step-change in vision and coding', description: 'Opus 4.5 launches as the most capable Claude model yet — step-change improvements in vision, coding, and computer use at a more accessible price than previous Opus models. Best model for complex specialized tasks and professional software engineering.', significance: 'major', href: 'https://www.anthropic.com/news/claude-opus-4-5', audience: ['for-you', 'for-builders'] },
  { event_date: '2025-11-18', org: 'Anthropic', title: 'Claude in Microsoft Foundry — Azure integration', description: 'Claude models come to Azure customers through Microsoft Foundry with Azure billing and OAuth authentication. Full Messages API access including extended thinking, prompt caching, PDF support, and Agent Skills.', significance: 'notable', href: 'https://platform.claude.com/docs/en/build-with-claude/claude-in-microsoft-foundry', audience: ['for-builders', 'for-admins'] },
  { event_date: '2024-11-07', org: 'Anthropic', title: 'Model Context Protocol (MCP) — open standard for tool connections', description: 'Anthropic releases MCP as an open protocol for connecting AI models to external tools and data sources. Other companies adopt it quickly, making MCP a de-facto standard. The shift from proprietary to standardized AI integrations.', significance: 'major', glossary_slug: 'mcp', href: 'https://www.anthropic.com/news/model-context-protocol', audience: ['for-builders', 'for-admins'] },
  { event_date: '2025-10-28', org: 'OpenAI', title: 'ChatGPT canvas + memory by default', description: 'OpenAI ships long-term memory as a default ChatGPT feature, and launches canvas — a structured writing and code workspace. Accelerates the shift from chatbot to persistent AI workspace.', significance: 'notable' },
  { event_date: '2025-10-16', org: 'Anthropic', title: 'Agent Skills — Claude works with Office files natively', description: 'Agent Skills launch in beta: pre-built Skills for PowerPoint, Excel, Word, and PDF files. Also supports custom Skills where you package your own domain expertise. Claude can now read and write Office documents without manual parsing — a major unlock for enterprise workflows.', significance: 'major', href: 'https://platform.claude.com/docs/en/agents-and-tools/agent-skills/overview', audience: ['for-you', 'for-builders'] },
  { event_date: '2025-10-15', org: 'Anthropic', title: 'Claude Haiku 4.5 — fastest model with near-frontier intelligence', description: 'Haiku 4.5 launches as the fastest and most capable Haiku yet — near-frontier performance for real-time applications, high-volume processing, and cost-sensitive deployments where speed matters more than maximum intelligence.', significance: 'notable', href: 'https://www.anthropic.com/news/claude-haiku-4-5', audience: ['for-builders'] },
  { event_date: '2025-09-29', org: 'Anthropic', title: 'Claude Sonnet 4.5 — built for complex agents and coding', description: 'Sonnet 4.5 launches with the highest intelligence of any Sonnet, built for complex agent workflows and coding tasks. Also ships: the memory tool (persistent context across conversations) and context editing for automatic conversation management.', significance: 'major', href: 'https://www.anthropic.com/news/claude-sonnet-4-5', audience: ['for-you', 'for-builders'] },
  { event_date: '2025-09-10', org: 'Anthropic', title: 'Web fetch tool — Claude reads any webpage', description: 'Web fetch tool launches in beta, letting Claude retrieve full content from any web page or PDF by URL. Pairs with web search for end-to-end research tasks.', significance: 'notable', href: 'https://platform.claude.com/docs/en/agents-and-tools/tool-use/web-fetch-tool', audience: ['for-builders'] },
  { event_date: '2025-06-12', org: 'Anthropic', title: 'Claude Code — agentic development in the terminal', description: 'Claude Code launches as a terminal-native development experience: reads codebases, runs commands, writes and edits files, and navigates full projects. Goes further than autocomplete into agentic development.', significance: 'major', glossary_slug: 'claude-code', href: 'https://claude.ai/code', audience: ['for-builders'] },
  { event_date: '2025-05-22', org: 'Anthropic', title: 'Claude Opus 4 + Sonnet 4 — the Claude 4 family launches', description: 'Anthropic ships the first Claude 4 models: Opus 4 for frontier tasks and Sonnet 4 for everyday use, both with extended thinking. Also ships: Files API, Code Execution tool, and MCP connector in the API. A step-change in what Claude can do in production.', significance: 'major', href: 'http://www.anthropic.com/news/claude-4', audience: ['for-you', 'for-builders'] },
  { event_date: '2025-05-07', org: 'Anthropic', title: 'Web search — Claude accesses the live internet', description: 'Web search launches in the API, giving Claude access to up-to-date information. Closes the biggest gap between Claude and web-native AI products.', significance: 'notable', href: 'https://platform.claude.com/docs/en/agents-and-tools/tool-use/web-search-tool', audience: ['for-you', 'for-builders'] },
  { event_date: '2025-05-05', org: 'OpenAI', title: 'GPT-4o — natively multimodal with real-time voice', description: 'GPT-4o ships as a single model handling voice, image, and text without switching modes. Real-time voice with sub-second latency. Brings the conversational AI interaction model much closer to reality.', significance: 'major' },
  { event_date: '2025-04-09', org: 'Meta', title: 'LLaMA 4 — frontier open-weights model', description: 'Meta releases LLaMA 4 with performance competitive with GPT-4-class models. Largest open-weights release to date. Reinforces that the gap between open-source and proprietary is closing faster than expected.', significance: 'notable', glossary_slug: 'meta-llama' },
  { event_date: '2025-02-24', org: 'Anthropic', title: 'Claude Sonnet 3.7 — extended thinking in production', description: "Claude Sonnet 3.7 ships as the first Claude model with extended thinking built in — a mode where Claude reasons step-by-step before answering. Near-instant responses or visible thinking, one model. Anthropic's first mainstream reasoning model.", significance: 'major', glossary_slug: 'extended-thinking', href: 'http://www.anthropic.com/news/claude-3-7-sonnet', audience: ['for-you', 'for-builders'] },
  { event_date: '2025-02-06', org: 'Industry', title: 'Agentic AI enters mainstream product conversation', description: 'The term "AI agents" crosses from research into mainstream product discussion. Every major AI lab ships or announces agentic products. The question shifts from "can AI do this?" to "how do you orchestrate AI to do this reliably?"', significance: 'context', glossary_slug: 'ai-agent' },
  { event_date: '2025-01-23', org: 'Anthropic', title: 'Citations API — source attribution for document work', description: 'Claude gains the ability to cite its sources when answering from documents — pointing to the exact passage it drew from. Major unlock for trust in enterprise document workflows and RAG applications.', significance: 'notable', href: 'https://platform.claude.com/docs/en/build-with-claude/citations', audience: ['for-builders'] },
  { event_date: '2025-01-12', org: 'Google', title: 'Gemini Advanced with Deep Research', description: 'Google ships Deep Research in Gemini Advanced — a mode that autonomously researches a topic across the web over several minutes and returns a structured report. First mainstream implementation of a multi-step research agent.', significance: 'notable' },
  // 2024
  { event_date: '2024-12-17', org: 'Anthropic', title: 'Batches, Token Counting, Prompt Caching — all go GA', description: 'Anthropic moves several API features to general availability: Message Batches API (50% cost reduction on batch jobs), Token Counting API, Prompt Caching (90% cost reduction), and PDF support. Also ships Go and Java SDKs.', significance: 'notable', href: 'https://platform.claude.com/docs/en/build-with-claude/batch-processing', audience: ['for-builders'] },
  { event_date: '2024-11-04', org: 'Anthropic', title: 'Claude Haiku 3.5 — fast, affordable, upgraded', description: 'Claude Haiku 3.5 launches as a fast, cost-efficient model for real-time applications and high-volume tasks. Better than Haiku 3 at a similar price point.', significance: 'notable', href: 'https://www.anthropic.com/claude/haiku', audience: ['for-builders'] },
  { event_date: '2024-10-22', org: 'Anthropic', title: 'Computer Use — Claude controls a desktop', description: 'Anthropic ships Computer Use in public beta: Claude can move a mouse, click, type, and navigate GUI applications. First mainstream API for AI-controlled computer interaction. Sets the foundation for desktop-level automation.', significance: 'major', href: 'https://www.anthropic.com/news/developing-computer-use', audience: ['for-builders'] },
  { event_date: '2024-09-12', org: 'OpenAI', title: 'o1 — reasoning model with explicit chain-of-thought', description: 'OpenAI releases o1, a model that reasons explicitly before answering. Significantly outperforms GPT-4 on math and science benchmarks. Introduces "reasoning model" as a distinct category from "chat model."', significance: 'major', glossary_slug: 'chain-of-thought-prompting' },
  { event_date: '2024-09-10', org: 'Anthropic', title: 'Console Workspaces — project-level API management', description: 'Workspaces launch in the Developer Console: custom spend limits, grouped API keys, usage tracking by project, and user roles. First real admin layer for teams using the Claude API.', significance: 'notable', href: 'https://www.anthropic.com/news/workspaces', audience: ['for-admins', 'for-builders'] },
  { event_date: '2024-08-14', org: 'Anthropic', title: 'Prompt Caching — 90% cost reduction on repeated context', description: 'Prompt caching launches in beta: cache and reuse prompt content to reduce costs by up to 90% and latency by up to 80%. Major cost unlock for applications using the same system prompt or documents repeatedly.', significance: 'notable', glossary_slug: 'prompt-caching', href: 'https://www.anthropic.com/news/prompt-caching', audience: ['for-builders'] },
  { event_date: '2024-06-20', org: 'Anthropic', title: 'Claude Sonnet 3.5 + Artifacts — a new interaction model', description: 'Claude Sonnet 3.5 launches with benchmark-leading coding performance. Artifacts ship alongside: a side-panel for code, documents, and interactive outputs. The shift from text responses to living, editable artifacts.', significance: 'major', glossary_slug: 'claude-artifacts', href: 'http://anthropic.com/news/claude-3-5-sonnet', audience: ['for-you'] },
  { event_date: '2024-03-04', org: 'Anthropic', title: 'Claude 3 family — Haiku, Sonnet, Opus', description: 'Anthropic ships the Claude 3 model family: three tiers for speed vs. capability tradeoffs. Opus leads on benchmarks. Haiku enables real-time, cost-efficient use cases. Establishes the tiered naming convention still in use today.', significance: 'major', href: 'https://www.anthropic.com/news/claude-3-family' },
  { event_date: '2024-02-08', org: 'Google', title: "Gemini 1.0 Ultra — Google's frontier model", description: "Google rebrands Bard to Gemini and ships the Ultra tier. Natively multimodal from architecture rather than retrofit. Signals Google's intent to compete directly with GPT-4 and Claude at the frontier.", significance: 'notable', glossary_slug: 'google-gemini' },
  // 2023
  { event_date: '2023-03-14', org: 'Anthropic', title: 'Claude 1 — Constitutional AI in production', description: 'Anthropic ships the first public Claude, trained using Constitutional AI — aligning model behavior using a set of principles rather than purely human feedback. First major alternative to GPT at capability scale.', significance: 'major', glossary_slug: 'constitutional-ai', href: 'https://www.anthropic.com/news/claude-1' },
  { event_date: '2023-03-14', org: 'OpenAI', title: 'GPT-4 — multimodal, significantly improved reasoning', description: 'GPT-4 launches with vision capabilities and measurably better reasoning than GPT-3.5. Triggers the "AI moment" for enterprise adoption.', significance: 'major' },
  // 2022
  { event_date: '2022-11-30', org: 'OpenAI', title: 'ChatGPT — the moment AI went mainstream', description: 'ChatGPT launches and reaches 100 million users in two months — the fastest consumer product adoption in history. Not the most capable model at the time, but the one that made AI accessible to everyone. Everything since has been a response to this moment.', significance: 'major', glossary_slug: 'large-language-model', href: 'https://openai.com/blog/chatgpt' },
] as const

// New events: Apr 18 – May 13, 2026 (+ Apr 14 which was missed in original)
const NEW_EVENTS = [
  // ── Aug 7–20, 2026 pass ──────────────────────────────────────────────────
  {
    event_date: '2026-08-20',
    org: 'Anthropic',
    title: 'Claude Academy — Anthropic\u2019s free training platform launches',
    description: "Anthropic launches Claude Academy at academy.claude.com, consolidating its training material into one platform: 22 courses, 119 tutorials, 148 role-specific use cases, and live webinars, all free. anthropic.com/learn now redirects there. The platform adds badges, completion tracking, personalized recommendations, and a Claude Academy Skill that suggests courses. Anthropic\u2019s stated philosophy is mindsets over features \u2014 durable habits like verifying in proportion to the stakes, rather than product behaviours that go stale.",
    significance: 'major',
    href: 'https://claude.com/blog/anthropics-approach-to-teaching-and-learning-ai',
    article_slug: 'claude-academy-guide',
    audience: ['for-you', 'for-admins', 'for-builders'],
  },
  {
    event_date: '2026-08-19',
    org: 'Anthropic',
    title: 'Computer use goes GA, browser use ships, Skills and Files APIs GA',
    description: "Four beta headers drop at once on the Claude API. Computer use becomes computer_toolset_20260801 with batch actions, zoom on by default, and per-member configuration. A new browser use toolset drives a browser your application hosts, reading the page\u2019s accessibility tree and offering element references, form input, and tab management rather than pixel-coordinate clicking. Agent Skills and the Skills API go GA, as does the Files API with file expiration and pagination. Supported on Fable 5, Mythos 5, Opus 5, Sonnet 5, and Opus 4.8.",
    significance: 'major',
    href: 'https://claude.com/blog/computer-use-skills-api-files-api',
    article_slug: 'computer-use-browser-use-ga',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-08-18',
    org: 'Anthropic',
    title: 'Console Workbench becomes Playground',
    description: "Workbench in the Claude Console is replaced by Playground, which supports every Messages API parameter, ships templates demonstrating code execution and web search, and shows the full SDK request alongside the API response for each run. The legacy Workbench and prompt tools APIs retired the previous day, so any automation calling them has already broken.",
    significance: 'notable',
    href: 'https://platform.claude.com/playground',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-08-14',
    org: 'Anthropic',
    title: 'Auto mode becomes the default in Claude Code',
    description: "New Claude Code sessions on Pro, Max, and Team plans now start in auto mode, where an AI classifier approves commands it judges safe instead of prompting for each one. Enterprise, the Claude API, Bedrock, Google Cloud, and Microsoft Foundry stay opt-in. Admins can set defaultMode or remove the option entirely with disableAutoMode. Anthropic notes the classifier does not eliminate risk and recommends manual review for production infrastructure changes.",
    significance: 'notable',
    href: 'https://claude.com/blog/auto-mode-default-in-claude-code',
    article_slug: 'claude-code-august-2026-updates',
    audience: ['for-builders', 'for-admins'],
  },
  {
    event_date: '2026-08-13',
    org: 'Google',
    title: 'Gemini 3.7 Flash GA \u2014 coding and agent workhorse',
    description: "Google ships gemini-3.7-flash to general availability, positioning it as its most intelligent workhorse model for coding and agents, with improvements across software engineering, web development, and agentic workflows. Introductory pricing runs through December 31, 2026. It follows Gemini 3.6 Flash and 3.5 Flash-Lite, which went GA on July 21.",
    significance: 'notable',
    href: 'https://ai.google.dev/gemini-api/docs/changelog',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-08-13',
    org: 'Anthropic',
    title: 'Claude Tag reads more of the Slack channel',
    description: "Claude Tag \u2014 Claude working as a tagged participant in Slack \u2014 gains fuller channel context, so a question asked mid-thread is answered against what the channel has already discussed rather than the tagged message alone. Anthropic published its own internal deployment alongside it, using Tag for self-service data analytics on ad-hoc questions.",
    significance: 'notable',
    href: 'https://claude.com/blog/claude-tag-now-reads-even-more-of-the-room',
    article_slug: 'claude-tag',
    audience: ['for-you', 'for-admins'],
  },
  {
    event_date: '2026-08-12',
    org: 'Anthropic',
    title: 'The Claude in Chrome side panel becomes Claude Cowork',
    description: "Anthropic folds the Claude in Chrome side panel into Cowork, so the browser surface now carries Cowork\u2019s task delegation and saved conversations rather than being a separate lightweight assistant. One fewer product surface to explain to a rollout, and one more place Cowork usage shows up in admin analytics.",
    significance: 'notable',
    href: 'https://claude.com/blog/cowork-chrome-side-panel',
    audience: ['for-you'],
  },
  {
    event_date: '2026-08-11',
    org: 'Anthropic',
    title: 'Compliance API reaches Cowork and Claude Code sessions on users\u2019 machines',
    description: "The Compliance API can now retrieve transcripts of Cowork and Claude Code sessions that run locally on employees\u2019 machines, in beta for Claude Enterprise. Three endpoints under /v1/compliance/apps/sessions/local list sessions, fetch metadata, and return transcripts, using the existing Compliance Access Key. It closes the last major blind spot for organizations that need a complete record of AI activity. A companion change adds an anthropic-workspace-id response header to the API.",
    significance: 'notable',
    href: 'https://claude.com/blog/compliance-api-cowork-and-claude-code',
    article_slug: 'claude-compliance-api',
    audience: ['for-admins'],
  },
  {
    event_date: '2026-08-10',
    org: 'Anthropic',
    title: 'Claude Sonnet 5 introductory pricing becomes permanent',
    description: "The $2 / $10 per million token introductory price for Claude Sonnet 5 is now the standard price. The increase to $3 / $15 scheduled for September 1, 2026 will not happen. Sonnet 5 is the model most production agent fleets run on, so a cost model built against the September increase has just gained back a third of its headroom.",
    significance: 'notable',
    href: 'https://platform.claude.com/docs/en/about-claude/pricing',
    article_slug: 'claude-sonnet-5',
    audience: ['for-builders', 'for-admins'],
  },
  {
    event_date: '2026-08-07',
    org: 'Anthropic',
    title: 'Managed Agents gain session budgets, an advisor, and geo pinning',
    description: "Four controls land on Claude Managed Agents. A session budget sets a hard cap on spend \u2014 a session that reaches it pauses with a budget_reached stop reason instead of starting new model requests. An advisor entry in the multiagent roster lets the primary thread consult a stronger model mid-turn for strategic guidance. inference_geo pins where inference runs, per agent or per session. And sessions can load Skills straight from a mounted GitHub repository\u2019s .claude/skills directory. On August 19, self-hosted sandboxes also gained memory stores, and the Console session viewer was rebuilt with per-tool statistics.",
    significance: 'major',
    href: 'https://platform.claude.com/docs/en/managed-agents/budgets',
    article_slug: 'managed-agents-budgets-guardrails',
    audience: ['for-builders', 'for-admins'],
  },
  {
    event_date: '2026-08-06',
    org: 'Anthropic',
    title: 'Self-hosted environments for Claude Code',
    description: "Claude Code sessions can run in an environment your organization hosts rather than Anthropic\u2019s, in public beta. It unblocks teams that could not adopt cloud-run sessions for data-residency reasons, and pairs with the self-hosted sandboxes shipped for Managed Agents in June.",
    significance: 'notable',
    href: 'https://support.claude.com/en/articles/12138966-release-notes',
    article_slug: 'claude-code-august-2026-updates',
    audience: ['for-builders', 'for-admins'],
  },
  {
    event_date: '2026-08-06',
    org: 'Anthropic',
    title: 'Skill and plugin security scanning for Claude Enterprise',
    description: 'Claude Enterprise gains automatic security scanning of third-party skills and plugins: when someone uploads or edits one, it is checked for malicious content before it can run. Skills and plugins are packaged instructions and tools that extend what Claude can do, and until now nothing inspected them on the way in. In beta on Enterprise plans.',
    significance: 'notable',
    href: 'https://support.claude.com/en/articles/12138966-release-notes',
    audience: ['for-admins'],
  },
  {
    event_date: '2026-08-05',
    org: 'Anthropic',
    title: 'Inference hooks — block a prompt before the model sees it',
    description: "Claude Enterprise organizations can route every governed prompt through a security server they run, which returns an allow or deny verdict before inference begins. A denied request never reaches the model. The hook runs on Anthropic's servers and covers claude.ai, Cowork, and Claude Code, with shadow mode, a rollout percentage, and role exclusions for staged deployment. In beta; not available on Bedrock or Google Cloud.",
    significance: 'notable',
    href: 'https://claude.com/blog/inference-hooks-inline-data-loss-prevention-for-claude-enterprise',
    article_slug: 'claude-inference-hooks',
    audience: ['for-admins', 'for-builders'],
  },
  {
    event_date: '2026-08-05',
    org: 'Anthropic',
    title: 'Claude Opus 4.1 retired',
    description: 'Anthropic retires Claude Opus 4.1 (`claude-opus-4-1-20250805`). Requests to the model now return an error rather than falling back. Anthropic recommends Claude Opus 5, which sits at the same $5/$25 per million tokens as Opus 4.8. Researchers can request continued access through the External Researcher Access Program.',
    significance: 'notable',
    href: 'https://platform.claude.com/docs/en/release-notes/overview',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-08-01',
    org: 'OpenAI',
    title: 'Astra solves ten open problems in mathematics and theoretical CS',
    description: 'OpenAI publishes "Ten advances in mathematics and theoretical computer science," reporting that an internal version of Astra — its next major model — produced new constructions, counterexamples, and bounds for ten problems that had seen no progress for at least a decade. Each argument is formalized as a machine-checkable Lean proof, published in the openai/ten-proofs repository, so verification does not depend on trusting the model. OpenAI put the token cost of finding all ten at roughly $2,000 at Sol API rates.',
    significance: 'major',
    href: 'https://openai.com/news/product-releases/',
  },
  {
    event_date: '2026-07-23',
    org: 'Anthropic',
    title: 'Voice mode runs on Opus and Sonnet, with connected tool actions',
    description: 'Claude voice mode moves onto the Opus and Sonnet model families, adds tool actions against connected Gmail and Slack accounts, supports eleven languages, and lets you switch models mid-conversation. Voice moves from a transcription front-end to something that can act on connected systems while you talk.',
    significance: 'notable',
    href: 'https://support.claude.com/en/articles/12138966-release-notes',
    audience: ['for-you'],
  },
  {
    event_date: '2026-07-02',
    org: 'Anthropic',
    title: 'Analytics and cost controls for Claude Enterprise',
    description: 'Claude Enterprise admins get usage and cost broken down by group and by individual user, an Analytics API that feeds tools like Datadog Cloud Cost Management and CloudZero, model defaults and entitlements that set which model conversations start on across chat, Cowork, and Claude Code, and spend threshold alerts firing at 75% and 90% of an org limit. Users get their own warnings at 75% and 95% plus an in-app way to request an increase before they hit the cap.',
    significance: 'notable',
    href: 'https://claude.com/blog/giving-admins-more-visibility-and-control-over-claude-usage-and-spend',
    article_slug: 'claude-enterprise-cost-controls',
    audience: ['for-admins'],
  },
  {
    event_date: '2026-07-28',
    org: 'Anthropic',
    title: 'MCP spec revision 2026-07-28 lands in Claude',
    description: "Anthropic ships support for the 2026-07-28 revision of the Model Context Protocol across Claude. MCP is the open standard — now governed by the Agentic AI Foundation — that lets Claude connect to external tools and data sources through a common interface rather than a bespoke integration per system. Spec revisions matter to anyone maintaining an MCP server: each one sets the contract that servers and clients agree on, and lagging behind a revision is how connectors quietly stop working.",
    significance: 'notable',
    href: 'https://claude.com/blog/bringing-mcp-2026-07-28-to-claude',
    article_slug: 'mcp-spec-2026-07-28',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-07-27',
    org: 'Anthropic',
    title: 'Cognizant partnership expands to enterprise client deployments',
    description: "Anthropic and Cognizant expand their partnership to bring Claude to Cognizant's enterprise client base. It follows the same pattern as the KPMG alliance (May 19) and the Blackstone/Goldman Sachs deployment joint venture (May 4): Anthropic reaching enterprises through systems integrators rather than direct sales alone. For IT leaders evaluating Claude, it increases the odds your existing consulting partner already has a Claude practice.",
    significance: 'notable',
    href: 'https://www.anthropic.com/news',
    audience: ['for-admins'],
  },
  {
    event_date: '2026-07-24',
    org: 'Anthropic',
    title: 'Claude Opus 5 — new flagship, thinking on by default, same price',
    description: "Claude Opus 5 (`claude-opus-5`) launches as a step-change over Opus 4.8 at unchanged pricing of $5/$25 per million tokens — half the cost of Fable 5, with Anthropic positioning it as close to Fable 5's frontier intelligence. It ships with a 1M token context window as both default and maximum, 128k max output, thinking on by default, and the full effort ladder (`low` through `max`), with effort as the primary control for reasoning depth. The prompt cache minimum drops to 512 tokens. One breaking change: `thinking: {\"type\": \"disabled\"}` at `xhigh` or `max` effort now returns a 400. Two behaviours to watch when migrating — `max_tokens` now has to cover thinking tokens, and the model self-verifies unprompted, so verification instructions carried over from older models cause over-verification. Fast mode for Opus 4.7 was removed the same day and now errors rather than falling back.",
    significance: 'major',
    href: 'https://www.anthropic.com/news/introducing-claude-opus-5',
    article_slug: 'claude-opus-5',
    audience: ['for-you', 'for-builders'],
  },
  {
    event_date: '2026-07-23',
    org: 'Anthropic',
    title: 'Four role-based Claude certifications',
    description: "Anthropic launches four role-based certifications for people who deploy Claude for customers, alongside a voice mode update that lets users think through hard problems by talking rather than typing. The certifications are the first formal credential Anthropic has offered around Claude deployment — relevant to the forward deployed engineer and agent manager roles that consultancies and enterprises are now hiring for, where 'how do I prove I can do this' has had no standard answer.",
    significance: 'notable',
    href: 'https://claude.com/blog',
    audience: ['for-you', 'for-admins'],
  },
  {
    event_date: '2026-07-17',
    org: 'Anthropic',
    title: 'Console Workbench and prompt tools APIs retire August 17',
    description: "The legacy Workbench at platform.claude.com/workbench is being sunset, with access ending August 17, 2026. Saved prompts, variables, and evals are not carried over to the replacement Workbench at /playground — you have to export anything you want to keep from the banner or Organizational Settings. The experimental prompt tools APIs retire on the same date: `/v1/experimental/generate_prompt`, `/improve_prompt`, and `/templatize_prompt` will return errors. Anything in your tooling that calls those endpoints needs replacing before mid-August.",
    significance: 'notable',
    href: 'https://platform.claude.com/docs/en/release-notes/overview',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-07-14',
    org: 'Anthropic',
    title: 'Claude Enterprise user management moves to the Admin API',
    description: "Claude Enterprise organisations can now manage people programmatically through the Admin API, in beta: list members, look them up by email, change roles, remove members, send and withdraw invites, manage groups and membership, and read custom roles. Group and custom-role calls need the `ce-user-management-2026-07-13` beta header; member and invite calls need none. This is the piece that lets identity automation — joiner/mover/leaver flows, offboarding scripts — cover Claude the same way it covers other SaaS. Anthropic also launched Claude for Teachers the same day.",
    significance: 'notable',
    href: 'https://platform.claude.com/docs/en/manage-claude/user-management',
    audience: ['for-admins'],
  },
  {
    event_date: '2026-07-09',
    org: 'OpenAI',
    title: 'GPT-5.6 goes public — Sol, Terra, Luna, plus ChatGPT Work',
    description: "OpenAI opens GPT-5.6 to the public two weeks after its government-gated preview, releasing all three tiers — Sol (flagship), Terra (mid-range), and Luna (fast and cheap). Alongside it comes ChatGPT Work, an agent built to carry out whole jobs rather than answer questions, and a small-business programme bundling ChatGPT Work and GPT-5.6 with training and in-person AI academies. OpenAI also shipped GPT-Live, a full-duplex voice generation that listens and speaks simultaneously. The public release lands two weeks before Claude Opus 5.",
    significance: 'major',
    href: 'https://openai.com/index/introducing-gpt-live/',
    audience: ['for-you', 'for-builders'],
  },
  {
    event_date: '2026-07-07',
    org: 'Meta',
    title: 'Muse Image — first image model from Meta Superintelligence Labs',
    description: "Meta ships Muse Image inside Meta AI, its first image generation model from Meta Superintelligence Labs. It uses reasoning to interpret complex prompts and blends multiple source photos into a single output. Rolling out to Facebook, Messenger, Instagram, and WhatsApp. It follows Muse Spark (April) as the second proprietary model from the lab, continuing Meta's move to run closed models alongside the open Llama line.",
    significance: 'notable',
    href: 'https://about.fb.com/news/2026/07/introducing-muse-image-meta-ai/',
  },
  {
    event_date: '2026-07-01',
    org: 'Meta',
    title: 'Meta Compute — Meta enters the cloud market',
    description: "Meta is building Meta Compute, a cloud infrastructure unit that will sell spare AI computing capacity to outside customers, putting it in direct competition with AWS, Microsoft Azure, and Google Cloud. It is the clearest sign yet that the AI buildout has produced more capacity than any single company's own products consume, and that compute itself is becoming the product. For enterprises, another potential venue for running models — and another vendor in an already crowded procurement conversation.",
    significance: 'notable',
    href: 'https://www.bloomberg.com/news/articles/2026-07-01/meta-compute-cloud',
    audience: ['for-admins'],
  },
  {
    event_date: '2026-06-18',
    org: 'Anthropic',
    title: 'Claude Code supports artifacts',
    description: "Claude Code gains artifact support, letting a session publish a rendered page — a report, a dashboard, a diagram — rather than leaving output as terminal text or a file on disk. It closes a gap between Claude Code and the web app for work whose deliverable is something a person needs to look at and share rather than run.",
    significance: 'notable',
    href: 'https://claude.com/blog',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-06-15',
    org: 'Anthropic',
    title: 'Claude Sonnet 4 and Opus 4 retired',
    description: "The original Claude 4 models — `claude-sonnet-4-20250514` and `claude-opus-4-20250514` — are retired, and all requests to them now return an error. Anthropic recommends Sonnet 4.6 and Opus 4.8 as replacements. Researchers can request continued access through the External Researcher Access Program. The retirement was announced with the Opus 4.7 launch in April, giving roughly two months of notice — a useful data point for how much runway to expect on future deprecations.",
    significance: 'notable',
    href: 'https://platform.claude.com/docs/en/about-claude/model-deprecations',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-07-01',
    org: 'Anthropic',
    title: 'Fable 5 and Mythos 5 restored — plus an industry jailbreak severity framework',
    description: "The US Commerce Department lifted the export controls on June 30, and Anthropic put Claude Fable 5 and Claude Mythos 5 back online worldwide on July 1 — across Claude.ai, the Claude Platform, Claude Code, and Cowork. To get there Anthropic shipped a new safety classifier that blocks the underlying jailbreak at a 99%+ rate, agreed to four government-collaboration terms, and — with Amazon, Microsoft, Google, and other Project Glasswing partners — proposed a shared jailbreak severity framework that scores each jailbreak on factors like capability gain (how far it takes a user beyond tools they already have). The three-week round trip is the case study for model-continuity planning: a frontier model can vanish and return on government action, so production systems need a wired-in fallback model and refusal handling regardless of which lab they build on.",
    significance: 'notable',
    href: 'https://www.anthropic.com/news/redeploying-fable-5',
    article_slug: 'claude-fable-5',
    audience: ['for-builders', 'for-admins'],
  },
  {
    event_date: '2026-06-30',
    org: 'Anthropic',
    title: 'Claude Sonnet 5 — cheaper agents, new tokenizer, cybersecurity safeguards',
    description: "Claude Sonnet 5 (`claude-sonnet-5`) launches as a drop-in upgrade to Sonnet 4.6 and the new default on Free and Pro, with its biggest gains in coding and agentic work — on Terminal-Bench 2.1 it even edges the Opus 4.8 flagship (80.4% vs 74.6%). It ships with a 1M token context by default, 128k max output, and adaptive thinking on by default, and is the first Sonnet-tier model with real-time cybersecurity safeguards (refused requests return a 200 with `stop_reason: 'refusal'`). Introductory pricing is $2/$10 per million tokens through Aug 31, 2026 (standard $3/$15). Three migration gotchas beyond the model-ID swap: manual extended thinking (`budget_tokens`) now returns 400, non-default sampling params (`temperature`/`top_p`/`top_k`) now return 400, and a new tokenizer produces ~30% more tokens for the same text — so recount prompts and revisit `max_tokens` and cost budgets before switching.",
    significance: 'major',
    href: 'https://platform.claude.com/docs/en/about-claude/models/whats-new-sonnet-5',
    article_slug: 'claude-sonnet-5',
    audience: ['for-you', 'for-builders'],
  },
  {
    event_date: '2026-06-30',
    org: 'Anthropic',
    title: 'Claude Science — a multi-agent workbench for researchers',
    description: "Anthropic launches Claude Science, a beta workbench (macOS and Linux; Pro, Max, Team, Enterprise) that pulls a researcher's scattered tools into one place — 60+ scientific databases and toolkits spanning genomics, single-cell work, proteomics, structural biology, and cheminformatics. Ask a question in plain language and a coordinating agent hands work to specialist sub-agents while a separate reviewer agent checks every citation and calculation as it goes. The bet is on workflow, not a new model: it runs on existing Claude models but packages the multi-agent orchestration and auditable outputs that regulated research demands. Anthropic is funding up to 50 'AI for Science' projects with up to $30k in credits, with applications open through July 15.",
    significance: 'notable',
    href: 'https://www.anthropic.com/news/claude-science-ai-workbench',
    article_slug: 'claude-science',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-06-30',
    org: 'Google',
    title: 'Gemini 3.5 Flash with Computer Use opens the 3.5 family',
    description: "Google opens its Gemini 3.5 family with Gemini 3.5 Flash — a faster, lower-cost model for coding, agents, multimodal tasks, and long-document work — now with built-in Computer Use that lets agents see, reason, and act across desktop, mobile, and browser environments. Alongside it, Gemini Omni Flash (a natively multimodal model for building custom video workflows) reaches public preview and Nano Banana 2 Lite ships as Google's fastest, most cost-efficient image model. Google signaled Gemini 3.5 Pro is still on the way. The Computer Use integration puts Google head-to-head with Anthropic's and OpenAI's agentic desktop-control offerings.",
    significance: 'notable',
    href: 'https://blog.google/innovation-and-ai/technology/ai/google-ai-updates-june-2026/',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-06-26',
    org: 'OpenAI',
    title: 'GPT-5.6 preview — Sol, Terra, Luna, gated to trusted partners at US government request',
    description: "OpenAI previews the GPT-5.6 family — Sol (flagship), Terra (balanced, ~2x cheaper than GPT-5.5), and Luna (fast, lowest-cost) — priced at $5/$30, $2.50/$15, and $1/$6 per million tokens. At the US government's request, access starts as a limited preview for roughly 20 trusted partners (whose participation was shared with the Administration) through the API and Codex, not ChatGPT, with broader release planned 'in the coming weeks.' It closely mirrors Anthropic's Fable 5 episode: frontier releases are now routed through government pre-release review. OpenAI also plans to run Sol on Cerebras hardware at up to 750 tokens/sec, and retired GPT-4.5 from ChatGPT the same day.",
    significance: 'notable',
    href: 'https://openai.com/index/previewing-gpt-5-6-sol/',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-06-23',
    org: 'Anthropic',
    title: 'Claude Tag — Claude joins Slack as a shared teammate',
    description: "Anthropic launches Claude Tag (beta, Team and Enterprise), moving the unit of AI collaboration from the private conversation to the shared Slack channel. One Claude joins the workspace as a persistent teammate with its own identity, its own memory, and admin-scoped access to tools and data. Tag it on a task and it breaks the work into stages and executes in the background, posting results back to the channel; with 'ambient' mode enabled it proactively flags relevant information and follows up on threads that have gone quiet. It replaces the old Claude-in-Slack integration (retiring Aug 3), with a 30-day window to migrate. A concrete template for the 'agent as coworker' pattern — Anthropic says its internal version now writes about 65% of its product team's code.",
    significance: 'notable',
    href: 'https://www.anthropic.com/news/introducing-claude-tag',
    audience: ['for-you', 'for-admins'],
  },
  {
    event_date: '2026-06-12',
    org: 'Anthropic',
    title: 'US government suspends Fable 5 and Mythos 5 — Anthropic disables both worldwide',
    description: "Three days after launch, Anthropic receives a US government export-control directive (June 12, 5:21pm ET) barring access to Fable 5 and Mythos 5 by any foreign national — inside or outside the US, including foreign-national Anthropic employees. To comply, Anthropic abruptly disables both models for all customers worldwide. The stated concern is national security tied to a method of bypassing Fable's safeguards; the directive gives no specifics, and Anthropic — which reviewed a demo tied to a few previously known minor vulnerabilities — calls it a misunderstanding and says it is working to restore access. All other Claude models (Opus 4.8, Sonnet, Haiku) are unaffected. A live lesson in cloud-AI continuity: a hosted model can vanish overnight, so production systems need a fallback model wired in.",
    significance: 'major',
    href: 'https://www.anthropic.com/news/fable-mythos-access',
    article_slug: 'claude-fable-5',
    audience: ['for-builders', 'for-admins'],
  },
  {
    event_date: '2026-06-09',
    org: 'Anthropic',
    title: 'Claude Fable 5 — new flagship model, with Claude Mythos 5 for Project Glasswing',
    description: "Anthropic launches Claude Fable 5 (`claude-fable-5`), its most capable widely released model, built for demanding reasoning and long-horizon agentic work. It ships with a 1M token context window by default, up to 128k output tokens, and always-on adaptive thinking (the older on/off thinking toggle is gone). Pricing is $10/$50 per million tokens — double Opus 4.8. It posts 95.0% on SWE-bench Verified and 80.3% on SWE-bench Pro (an 11-point jump over Opus 4.8). The integration-breaking change: built-in safety classifiers can decline a request, returning `stop_reason: \"refusal\"` as a successful 200, so apps need refusal handling and a fallback path to another model. Claude Mythos 5 (`claude-mythos-5`) shares the same capabilities without the classifiers and is limited to Project Glasswing partners. Free on Pro/Max/Team/Enterprise through June 22, then metered against credits.",
    significance: 'major',
    href: 'https://platform.claude.com/docs/en/about-claude/models/introducing-claude-fable-5-and-claude-mythos-5',
    article_slug: 'claude-fable-5',
    audience: ['for-you', 'for-builders'],
  },
  {
    event_date: '2026-06-09',
    org: 'Anthropic',
    title: 'Claude Managed Agents — self-hosted sandboxes, scheduled runs, and secret vaults',
    description: "Anthropic expands Claude Managed Agents along three lines. Self-hosted sandboxes reach general availability on the Claude API and Claude Platform on AWS: tool execution runs on infrastructure you control and can reach your private MCP servers, while Claude keeps running on Anthropic's side. Agents can now run on a schedule without an external trigger, and environment variables (API keys, credentials) can be stored in encrypted vaults instead of being passed in per request. Together these move Managed Agents closer to production use inside enterprise security boundaries.",
    significance: 'notable',
    href: 'https://claude.com/blog',
    article_slug: 'claude-managed-agents-self-hosted',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-06-08',
    org: 'OpenAI',
    title: 'OpenAI files confidential S-1 for an IPO',
    description: "OpenAI confidentially submits a draft S-1 registration to the SEC — the legal step that precedes an initial public offering. Reported valuations run $730B–$852B against annualized revenue above $25B. The company says it has not set a timeline and that some plans are easier to pursue while still private. It follows Anthropic's own confidential IPO filing in late May, signaling that the two largest frontier labs are both moving toward public-market scale and scrutiny.",
    significance: 'context',
    href: 'https://openai.com/index/openai-submits-confidential-s-1/',
  },
  {
    event_date: '2026-06-05',
    org: 'Anthropic',
    title: 'Claude Opus 4.1 retirement notice',
    description: "Anthropic notifies developers that Claude Opus 4.1 will be retired on the Claude API. With Opus 4.8 and now Fable 5 available, teams still calling `claude-opus-4-1` need to migrate to a current model. A reminder that pinning a specific model ID carries an end-of-life clock — production code should plan for model migration as routine maintenance.",
    significance: 'notable',
    href: 'https://platform.claude.com/docs/en/about-claude/model-deprecations',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-06-03',
    org: 'OpenAI',
    title: 'ChatGPT adds "Dreaming" memory; Codex updates for every role',
    description: "OpenAI ships a new ChatGPT memory system it calls Dreaming, which reviews past conversations to keep preferences and context fresh across sessions. The same week it expands Codex with role-specific updates aimed at non-developers — analysts, marketers, operators, and designers — who now make up a fast-growing share of Codex's 5M+ weekly users. Both moves push ChatGPT further from a chat box toward a persistent, cross-role work assistant.",
    significance: 'notable',
    href: 'https://openai.com/news/product-releases/',
    audience: ['for-you'],
  },
  {
    event_date: '2026-06-03',
    org: 'Meta',
    title: 'Meta Business Agent — AI agents for businesses across WhatsApp, Messenger, Instagram',
    description: "Mark Zuckerberg unveils Meta Business Agent, an AI agent businesses can deploy across WhatsApp, Messenger, and Instagram to answer customer inquiries, recommend products, and book appointments. It ships inside a business tier of Meta One and is billed on a consumption basis for large WhatsApp Business Platform users. Meta's clearest move yet to monetize AI beyond advertising. Separately, Meta's Muse Spark model API for developers slipped again with no firm launch date.",
    significance: 'notable',
    href: 'https://www.cnbc.com/2026/06/03/meta-business-agent-is-zuckerberg-latest-effort-to-diversify-from-ads.html',
  },
  {
    event_date: '2026-06-02',
    org: 'Microsoft',
    title: 'Build 2026 — Copilot "Autopilots" and Scout, plus seven new MAI models',
    description: "At Build 2026, Microsoft introduces Autopilots — a new category of always-on, autonomous agents — starting with Scout, which works in the background across Teams, Outlook, OneDrive, SharePoint, browsers, and local files and acts without being prompted each time. Microsoft also ships seven new in-house MAI models (headlined by MAI-Thinking-1, a 35B reasoning model with a 256K context built without distillation) and Copilot Platform, a set of APIs and a runtime for embedding Copilot agents in any app. The framing shift: from AI-as-assistant to AI-as-operator.",
    significance: 'notable',
    href: 'https://www.theregister.com/ai-and-ml/2026/06/03/no_longer_just_a_copilot/',
    audience: ['for-admins'],
  },
  {
    event_date: '2026-06-02',
    org: 'OpenAI',
    title: 'Codex generally available on AWS Bedrock; Sites and annotations added',
    description: "OpenAI makes its frontier models and Codex generally available on AWS through Amazon Bedrock, and expands Codex with role-specific plugins, Sites (sharing interactive workspace apps and websites), and annotations for refining documents, spreadsheets, and slides. Codex now has more than 5 million weekly users, and non-developers — analysts, marketers, operators, designers, bankers — make up about 20% of them, growing more than 3x faster than developers.",
    significance: 'notable',
    href: 'https://openai.com/news/',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-05-28',
    org: 'Anthropic',
    title: 'Claude Opus 4.8 — new flagship, effort defaults to high, fast mode 3x cheaper',
    description: "Anthropic launches Claude Opus 4.8 (claude-opus-4-8), its most capable generally available model. Pricing is unchanged at $5/$25 per million tokens. The effort parameter now defaults to high across all surfaces, a 1M token context window ships by default, and max output rises to 128k tokens. Fast mode runs ~2.5x faster at $10/$50 — three times cheaper than prior Opus fast mode. New mid-conversation system messages let instructions change without breaking the prompt cache. Anthropic reports it beats GPT-5.5 on 12+ benchmarks (SWE-Bench Pro 69.2% vs 58.6%) and is ~4x less likely than 4.7 to let a code flaw pass in review. Migration from Opus 4.7 is a model-name swap — no new breaking changes.",
    significance: 'major',
    href: 'https://www.anthropic.com/news/claude-opus-4-8',
    article_slug: 'claude-opus-4-8',
    audience: ['for-you', 'for-builders'],
  },
  {
    event_date: '2026-05-28',
    org: 'Anthropic',
    title: 'Dynamic Workflows in Claude Code — Claude orchestrates its own agent swarm',
    description: "Shipping alongside Opus 4.8 as a research preview, Dynamic Workflows let Claude author a multi-step plan and orchestrate work across tens to hundreds — up to roughly a thousand — subagents running in the background. Built for jobs a single context window can't hold: codebase-scale migrations across hundreds of thousands of lines, sweeping audits, large repetitive transforms. Distinct from sub-agents, Agent Teams, and the `claude agents` terminal mode — here Claude decides the structure and you approve the plan rather than each step.",
    significance: 'notable',
    href: 'https://code.claude.com/docs',
    article_slug: 'claude-code-dynamic-workflows',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-05-28',
    org: 'Anthropic',
    title: 'Series H — $65B raised at $965B valuation; confidential IPO filing',
    description: "Anthropic closes a $65B Series H round at a $965B post-money valuation, with run-rate revenue reported to have crossed $47B earlier in May. The same day, it confidentially files for an initial public offering — setting up a public-market test of the AI boom. Together they mark Anthropic's transition toward public-company scale and scrutiny.",
    significance: 'context',
    href: 'https://www.cbsnews.com/news/anthropic-ipo-confidential-filing-claude-ai/',
  },
  {
    event_date: '2026-05-14',
    org: 'Anthropic',
    title: 'Subscription billing change — programmatic usage moves to a separate credit pool',
    description: "Anthropic announces that from June 15, 2026, programmatic Claude usage (the Agent SDK, `claude -p` headless mode, Claude Code GitHub Actions, and third-party apps using Agent SDK credentials) stops drawing from a subscription's rate limits and instead draws from a separate monthly dollar credit metered at API list prices — $20 for Pro, $100 for Max 5x, $200 for Max 20x, per user, no rollover. Interactive Claude Code and web chat are unchanged. The change ends uncapped subsidized automated usage and is effectively a large price increase for heavy programmatic workloads.",
    significance: 'notable',
    href: 'https://thenewstack.io/anthropic-agent-sdk-credits/',
    article_slug: 'claude-subscription-credit-changes',
    audience: ['for-builders', 'for-admins'],
  },
  {
    event_date: '2026-04-14',
    org: 'Anthropic',
    title: 'Claude Code desktop redesign — parallel sessions, integrated editor',
    description: "Claude Code's desktop app ships a major redesign: a sessions sidebar for running multiple tasks in parallel, an integrated terminal and file editor with faster diffs, expanded preview pane, side chat (⌘+;) for asking questions without interrupting the main session, drag-and-drop workspace, and SSH support on Mac. The shift from a single-task CLI to a multi-session coding environment.",
    significance: 'notable',
    href: 'https://code.claude.com/docs/en/changelog',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-04-23',
    org: 'OpenAI',
    title: 'GPT-5.5 — next step toward an AI super-app',
    description: "OpenAI releases GPT-5.5 and GPT-5.5 Pro, framing it as a step toward a unified AI 'super-app.' Available via API (as chat-latest) from April 24. Positions ChatGPT closer to a full-featured work assistant rather than a pure chat interface.",
    significance: 'notable',
    href: 'https://openai.com/index/introducing-gpt-5-5/',
  },
  {
    event_date: '2026-04-30',
    org: 'Industry',
    title: '$700 billion — Big Tech AI infrastructure spending in 2026',
    description: "Microsoft, Google, Meta, Amazon, and others are on track to collectively spend ~$700 billion on AI infrastructure in 2026, nearly double 2025 levels. Meta alone guided $115–135B in capex. No clear ceiling: every major hyperscaler is accelerating, treating AI compute as the defining infrastructure race of the decade.",
    significance: 'context',
    href: 'https://fortune.com/2026/04/30/big-tech-hyperscalers-will-spend-700-billion-on-ai-infrastructure-this-year-with-no-clear-end-in-sight-eye-on-ai/',
  },
  {
    event_date: '2026-05-04',
    org: 'Anthropic',
    title: 'Enterprise AI services company — Anthropic + Blackstone + Goldman',
    description: "Anthropic, Blackstone, Hellman & Friedman, and Goldman Sachs announce a new AI services company targeting mid-sized businesses. The joint venture deploys Claude into core operations across sectors — the first major move by Anthropic to own the services layer, not just the model.",
    significance: 'notable',
    href: 'https://www.anthropic.com/news/enterprise-ai-services-company',
    audience: ['for-admins'],
  },
  {
    event_date: '2026-05-05',
    org: 'OpenAI',
    title: 'GPT-5.5 Instant — new default ChatGPT model',
    description: "OpenAI ships GPT-5.5 Instant as the default model for all ChatGPT users, replacing GPT-5.3 Instant. Produces 52.5% fewer hallucinated claims on high-stakes prompts (medicine, law, finance). Can search past conversations, files, and Gmail for personalized answers. GPT-5.3 Instant remains available to paid users for three months before retirement.",
    significance: 'notable',
    href: 'https://openai.com/index/gpt-5-5-instant/',
  },
  {
    event_date: '2026-05-07',
    org: 'Anthropic',
    title: 'Managed Agents: Dreaming, Outcomes, multi-agent orchestration',
    description: "Anthropic ships three new capabilities for Managed Agents. Dreaming: agents review their own past sessions, extract patterns, and self-improve over time. Outcomes: a separate grading agent scores completed tasks and re-runs them until they hit quality thresholds — lifted document generation quality 10.1% on benchmarks. Multi-agent orchestration: a lead agent breaks jobs into pieces and delegates each to a specialist with its own model, prompt, and tools running in parallel on a shared filesystem.",
    significance: 'major',
    href: 'https://9to5mac.com/2026/05/07/anthropic-updates-claude-managed-agents-with-three-new-features/',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-05-08',
    org: 'Anthropic',
    title: 'Claude Platform on AWS — generally available',
    description: "Anthropic's native Claude Platform experience arrives on AWS as a GA service — the first cloud provider to offer it. AWS customers get the full Claude API (Messages, Files, Batches, Managed Agents, Agent Skills, code execution, web tools) through native AWS endpoints, unified with existing AWS billing, authentication, and security controls. No separate Anthropic contract needed. Anthropic simultaneously commits $100B+ to AWS over ten years.",
    significance: 'major',
    href: 'https://aws.amazon.com/about-aws/whats-new/2026/05/claude-platform-aws/',
    audience: ['for-builders', 'for-admins'],
  },
  {
    event_date: '2026-05-12',
    org: 'Google',
    title: 'Android Show 2026 — Gemini Intelligence across Android',
    description: "Google's Android Show 2026 centers on Gemini Intelligence: on-device AI that automates complex tasks, summarizes web content, fills forms, and includes Rambler (polishes voice messages or builds custom widgets from natural language). New Googlebooks AI-first laptops announced. Gemini comes to Chrome. Rolling out to Samsung and Pixel phones first, then broader Android. Signals the shift from Gemini-as-chatbot to Gemini-as-OS-layer.",
    significance: 'notable',
    href: 'https://techcrunch.com/2026/05/12/everything-google-announced-at-its-android-show-from-googlebooks-to-vibe-coded-widgets/',
  },
  {
    event_date: '2026-05-19',
    org: 'Anthropic',
    title: 'Andrej Karpathy joins Anthropic',
    description: "Karpathy — founding OpenAI member, former Tesla Autopilot lead, and the foremost AI educator on the internet — announces he has joined Anthropic to get back to R&D. The hire is widely read as a significant talent signal: CTOs of publicly traded companies and top researchers across the industry have been choosing individual contributor roles at Anthropic over running organizations. Karpathy's publicly stated focus: the next few years of LLM development will be \"especially formative.\"",
    significance: 'major',
    href: 'https://x.com/karpathy/status/1924560535634038954',
    article_slug: 'karpathy-joins-anthropic',
    audience: ['for-you', 'for-builders'],
  },
  {
    event_date: '2026-05-19',
    org: 'Anthropic',
    title: 'claude agents — parallel multi-agent terminal mode in Claude Code',
    description: "Anthropic ships `claude agents`, a new terminal mode that lets users run multiple independent agent tasks simultaneously. Each task runs as its own agent; keyboard navigation moves between them. Distinct from the desktop parallel sessions sidebar — this is the headless/terminal-native equivalent. Enables parallel research, builds, and pipelines without GUI.",
    significance: 'notable',
    href: 'https://docs.anthropic.com/en/docs/claude-code/overview',
    article_slug: 'claude-agents-command',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-05-20',
    org: 'Google',
    title: 'Google I/O 2026 — Gemini Spark preview, Gemini 3.5 Flash',
    description: "Google I/O 2026's AI announcements: Gemini Spark (leaked/previewed) — a new agentic surface inside the Gemini app with virtual computers, long agent trajectories, canvas, deep research, and connections across Google Workspace. Gemini 3.5 Flash releases but falls short of frontier expectations — widely noted as faster but not competitive with GPT-5.5 or Claude Opus 4.7 on complex reasoning. Gemini Omni video model also announced but trails Sora and Kling. Google's main challenge: no clear unified super-app strategy (Gemini vs. AI Studio vs. Project IDX).",
    significance: 'notable',
    href: 'https://io.google/2026/',
    audience: ['for-you', 'for-admins'],
  },
  {
    event_date: '2026-05-20',
    org: 'OpenAI',
    title: 'Codex adds /goal mode and plugin sharing',
    description: "OpenAI ships two meaningful Codex updates: /goal mode, which lets agents run autonomously for hours (or more than a day) toward a stated high-level objective rather than stopping after each command; and plugin sharing, which lets team members publish workflow plugins to the entire workspace. Design mode (screenshot + annotation for UI iteration) also ships. Together these move Codex significantly closer to a unified super-app that handles both coding and long-horizon knowledge work.",
    significance: 'notable',
    href: 'https://openai.com/codex',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-05-21',
    org: 'Industry',
    title: 'XAI acquires Cursor — $60B valuation, Composer 2.5',
    description: "Elon Musk's XAI (backed by SpaceX compute infrastructure) acquires Cursor at roughly $60 billion with a $10 billion opt-out clause. The compute access enables Composer 2.5, a new coding model that is significantly faster and cheaper than equivalents on Claude or Codex — early reports put it at near-frontier quality for front-end work at a fraction of the token cost. Cursor announces intent to become a full 'coding and knowledge work' platform, adding automations and a marketplace alongside its existing in-app browser.",
    significance: 'notable',
    href: 'https://cursor.com',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-05-21',
    org: 'Anthropic',
    title: 'Claude Compliance API + 28 enterprise security integrations',
    description: 'Anthropic ships the Claude Compliance API and 28 launch-partner integrations across DLP (Microsoft Purview, Nightfall, Forcepoint), SIEM (Splunk, Securonix, Sumo Logic), CASB (Netskope, Zscaler), identity (Okta, CrowdStrike Falcon), eDiscovery (Relativity, Logikcull), and AI security posture (Wiz, Orca, Lacework). Enterprise admins get programmatic access to all Claude usage data — request-level prompts and responses — for compliance, eDiscovery, and security monitoring. The Compliance API and Security Ingestion API are distinct: compliance routes data to legal/HR, security routes alerts to SOC tooling.',
    significance: 'major',
    href: 'https://www.securityweek.com/anthropic-expands-claudes-enterprise-security-reach-with-28-new-integrations/',
    article_slug: 'claude-compliance-api',
    audience: ['for-admins'],
  },
  {
    event_date: '2026-05-13',
    org: 'Anthropic',
    title: 'Claude for Small Business — pre-built connectors and workflows',
    description: 'Anthropic launches Claude for Small Business: a bundle of pre-built connectors and ready-to-run workflows targeting companies without a dedicated IT or AI team. Seven integrations at launch: QuickBooks, PayPal, HubSpot, Canva, DocuSign, Google Workspace, Microsoft 365. Claude can read live data from connected tools and perform tasks without manual copy-paste. Available on Claude Pro and higher.',
    significance: 'notable',
    href: 'https://www.anthropic.com/news/claude-for-small-business',
    article_slug: 'claude-for-small-business',
    audience: ['for-you', 'for-admins'],
  },
  {
    event_date: '2026-05-13',
    org: 'OpenAI',
    title: 'OpenAI launches The Deployment Company — $10B FDE venture',
    description: "OpenAI launches a majority-owned deployment company with McKinsey, Bain, and Capgemini, funded at $10B+. Simultaneously acquires Tomoro, a 150-person forward deployed engineering firm, to staff it immediately. The Deployment Company puts OpenAI engineers inside enterprise clients to build production AI systems against their actual infrastructure — a direct copy of Palantir's FDE model. Launched within days of Anthropic's $1.5B JV with Blackstone and Goldman Sachs.",
    significance: 'notable',
    href: 'https://openai.com/index/openai-launches-the-deployment-company/',
    article_slug: 'why-anthropic-openai-copied-palantir',
    audience: ['for-admins', 'for-builders'],
  },
  {
    event_date: '2026-05-18',
    org: 'Anthropic',
    title: 'Anthropic acquires Stainless — SDK and MCP generation toolchain',
    description: 'Anthropic acquires Stainless for $300M+. Stainless automates generation of SDKs, CLIs, and MCP servers from API specs, and previously generated all official Anthropic, OpenAI, Google, Cloudflare, and Meta SDKs. Bringing Stainless in-house means Anthropic now controls the SDK pipeline and MCP server generation toolchain. All hosted Stainless products are being wound down; existing customers keep their generated SDKs.',
    significance: 'notable',
    href: 'https://techcrunch.com/2026/05/18/anthropic-has-acquired-the-dev-tools-startup-used-by-openai-google-and-cloudflare/',
    audience: ['for-builders'],
  },
  {
    event_date: '2026-05-19',
    org: 'Anthropic',
    title: 'KPMG global alliance — 276,000-person workforce deployment',
    description: "KPMG signs a global alliance with Anthropic to deploy Claude across its 276,000-person workforce and embed Claude Cowork and Managed Agents into KPMG's Digital Gateway platform. Launch use cases: tax, legal, private equity. KPMG also announces KPMG Blaze — a product built on Claude Code for modernizing legacy IT systems inside private equity portfolio companies. Second Big Four firm to go all-in on Claude in one month, following PwC's announcement on May 14.",
    significance: 'notable',
    href: 'https://www.anthropic.com/news/anthropic-kpmg',
    audience: ['for-admins'],
  },
  {
    event_date: '2026-05-22',
    org: 'Anthropic',
    title: 'Project Glasswing: 10,000 vulnerabilities found in first month',
    description: "Anthropic publishes the first update on Project Glasswing — its controlled-access cybersecurity initiative using the unreleased Claude Mythos Preview model. In the first month, Glasswing partners discovered 10,000+ software vulnerabilities. The open-source scan alone (1,000+ widely used projects) flagged 6,202 high/critical vulnerabilities with a 90.6% confirmed true-positive rate. Partners include AWS, Apple, Cisco, CrowdStrike, Google, JPMorganChase, Microsoft, NVIDIA, Palo Alto Networks, and now Verizon.",
    significance: 'notable',
    href: 'https://www.helpnetsecurity.com/2026/05/26/anthropic-project-glasswing-update/',
    audience: ['for-admins', 'for-builders'],
  },
  {
    event_date: '2026-05-23',
    org: 'Anthropic',
    title: 'Claude Code v2.1.149 — /usage cost breakdown, enterprise MCP setting',
    description: "Claude Code v2.1.149 ships two practitioner-relevant features: /usage, a new command that shows per-category token cost breakdowns mid-session (context vs. tools vs. output vs. cache); and allowAllClaudeAiMcps, an enterprise setting that blanket-approves all Claude.ai cloud MCP connectors without per-server admin review. Also in the v2.1.147-v2.1.152 range: /simplify renamed to /code-review, /code-review --fix auto-applies findings, Auto mode runs without a per-session consent prompt, and VS Code 1.121 adds remote agent sessions that survive laptop disconnect.",
    significance: 'notable',
    href: 'https://releasebot.io/updates/anthropic/claude-code',
    article_slug: 'claude-code-may-2026-updates',
    audience: ['for-builders'],
  },
] as const

function toRow(e: Record<string, unknown>) {
  return {
    event_date: e.event_date,
    org: e.org,
    title: e.title,
    description: e.description,
    significance: e.significance,
    glossary_slug: (e.glossary_slug ?? null) as string | null,
    href: (e.href ?? null) as string | null,
    article_slug: (e.article_slug ?? null) as string | null,
    audience: (e.audience ?? []) as string[],
    published: true,
  }
}

async function seed() {
  const allEvents = [...EVENTS, ...NEW_EVENTS]
  console.log(`Seeding ${allEvents.length} timeline events (${EVENTS.length} original + ${NEW_EVENTS.length} new)...`)

  const rows = allEvents.map(e => toRow(e as unknown as Record<string, unknown>))

  const { error } = await supabase
    .from('timeline_events')
    .upsert(rows, { onConflict: 'event_date,org,title' })

  if (error) {
    console.error('Seed failed:', error)
    process.exit(1)
  }

  console.log(`✓ Seeded ${rows.length} events`)
}

seed()
